In [16]:
# Loading libraries
suppressPackageStartupMessages({
  library(ENmix)
  library(IlluminaHumanMethylationEPICmanifest)
  library(IlluminaHumanMethylationEPICanno.ilm10b2.hg19)
  library(parallel)
  library(methylCIPHER)
    library(glmnet);
    library(EpiDISH);
    library(dnaMethyAge);
    library(prcPhenoAge);
    library(DunedinPoAm38)
})

In [2]:
# Reading phenotypic data of DNAm in UTHealth cohort
mf = "/gpfs/gibbs/pi/montalvo-ortiz/epigenomics/braindata/collaborations/consuelobassdata/brain_dataset/meta_BA9_brainbank_methylation_sub_3-29-22.csv"
mf = read.csv(mf)
mf$name <- paste0("BRA_", mf$Sentrix_ID)
head(mf$name)

[1] "BRA_201465920012_R01C01" "BRA_201465920012_R02C01"
[3] "BRA_201465920012_R03C01" "BRA_201465920012_R04C01"
[5] "BRA_201465920012_R05C01" "BRA_201465920012_R06C01"

In [3]:
load("/vast/palmer/scratch/montalvo-ortiz/jjm262/00tclocks/00uthealth/00databases/05epigenome/00uthealth_brain-07312025.RData")
load("/vast/palmer/scratch/montalvo-ortiz/jjm262/00tclocks/00uthealth/00databases/05epigenome/00uthealth_brain-07302025.RData")

In [4]:
# setting cores
num_threads <- detectCores() - 1
print(num_threads)
# set working directory
wkdir="/vast/palmer/scratch/montalvo-ortiz/jjm262/00tclocks/00uthealth/00databases/05epigenome"
setwd(wkdir)
ls()

[1] 47

[1] "beta"        "mdat"        "mf"          "num_threads" "pheno"
[6] "qc"          "wkdir"

In [5]:
# Perform SVA analysis
path="/gpfs/gibbs/pi/montalvo-ortiz/epigenomics/braindata/collaborations/consuelobassdata/brain_dataset/idat_brain"
suppressMessages({
  rgSet <- readidat(path = path, recursive = TRUE, force = TRUE)
})
sva <- ctrlsva(rgSet)
sva = as.data.frame(sva)
sva$name = rownames(sva)

BRA_201465920012_R01C01 BRA_201465920012_R02C01 BRA_201465920012_R03C01
                1051943                 1051943                 1051943
BRA_201465920012_R04C01 BRA_201465920012_R05C01 BRA_201465920012_R06C01
                1051943                 1051943                 1051943
BRA_201465920012_R07C01 BRA_201465920012_R08C01 BRA_201465920048_R01C01
                1051943                 1051943                 1051943
BRA_201465920048_R02C01 BRA_201465920048_R03C01 BRA_201465920048_R04C01
                1051943                 1051943                 1051943
BRA_201465920048_R05C01 BRA_201465920048_R06C01 BRA_201465920048_R07C01
                1051943                 1051943                 1051943
BRA_201465920048_R08C01 BRA_201532190145_R01C01 BRA_201532190145_R02C01
                1051943                 1051815                 1051815
BRA_201532190145_R03C01 BRA_201532190145_R04C01 BRA_201532190145_R05C01
                1051815                 1051815                 1051815
BRA_201532190145_R06C01 BRA_201532190145_R07C01 BRA_201532190145_R08C01
                1051815                 1051815                 1051815
BRA_202273260185_R01C01 BRA_202273260185_R02C01 BRA_202273260185_R03C01
                1051815                 1051815                 1051815
BRA_202273260185_R04C01 BRA_202273260185_R05C01 BRA_202273260185_R06C01
                1051815                 1051815                 1051815
BRA_202273260185_R07C01 BRA_202273260185_R08C01 BRA_202273260186_R01C01
                1051815                 1051815                 1051815
BRA_202273260186_R02C01 BRA_202273260186_R03C01 BRA_202273260186_R04C01
                1051815                 1051815                 1051815
BRA_202273260186_R05C01 BRA_202273260186_R06C01 BRA_202273260186_R07C01
                1051815                 1051815                 1051815
BRA_202273260186_R08C01 BRA_202784980012_R01C01 BRA_202784980012_R02C01
                1051815                 1051815                 1051815
BRA_202787550031_R01C01 BRA_202787550031_R02C01 BRA_202787550031_R03C01
                1051815                 1051815                 1051815
BRA_202787550031_R04C01 BRA_202787550031_R05C01 BRA_202787550031_R06C01
                1051815                 1051815                 1051815
BRA_202787550031_R07C01 BRA_202787550031_R08C01 BRA_202787550059_R01C01
                1051815                 1051815                 1051815
BRA_202787550059_R02C01 BRA_202787550059_R03C01 BRA_202787550059_R04C01
                1051815                 1051815                 1051815
BRA_202787550059_R05C01 BRA_202787550059_R06C01 BRA_202787550059_R07C01
                1051815                 1051815                 1051815
BRA_202787550059_R08C01 BRA_202787550060_R01C01 BRA_202787550060_R02C01
                1051815                 1051815                 1051815
BRA_202787550060_R03C01 BRA_202787550060_R04C01 BRA_202787550060_R05C01
                1051815                 1051815                 1051815
BRA_202787550060_R06C01 BRA_202787550060_R07C01 BRA_202787550060_R08C01
                1051815                 1051815                 1051815
BRA_205016910016_R01C01 BRA_205016910016_R02C01 BRA_205016910016_R04C01
                1051943                 1051943                 1051943
BRA_205016910016_R05C01 BRA_205016910016_R06C01 BRA_205016910016_R07C01
                1051943                 1051943                 1051943
BRA_205016910016_R08C01 BRA_205016910070_R01C01 BRA_205016910070_R02C01
                1051943                 1051943                 1051943
BRA_205016910070_R03C01 BRA_205016910070_R04C01 BRA_205016910070_R05C01
                1051943                 1051943                 1051943
BRA_205016910070_R06C01 BRA_205016910070_R07C01 BRA_205016910070_R08C01
                1051943                 1051943                 1051943
BRA_205062740040_R01C01 BRA_205062740040_R02C01 BRA_205062740040_R03C01
                1051943                 1051943                 1051943
BRA_205062740040_R04C01 BRA_205062740040_R05C01 BRA_205062740040_R06C01
                1051943                 1051943                 1051943
BRA_205062740040_R07C01 BRA_205062740040_R08C01 BRA_205062740052_R01C01
                1051943                 1051943                 1051943
BRA_205062740052_R02C01 BRA_205062740052_R03C01 BRA_205062740052_R05C01
                1051943                 1051943                 1051943
BRA_205062740052_R06C01 BRA_205062740052_R07C01 BRA_205062740052_R08C01
                1051943                 1051943                 1051943
BRA_205062740070_R01C01 BRA_205062740070_R02C01 BRA_205062740070_R03C01
                1051943                 1051943                 1051943
BRA_205062740070_R04C01 BRA_205062740070_R05C01 BRA_205062740070_R06C01
                1051943                 1051943                 1051943
BRA_205062740070_R07C01 BRA_205062740070_R08C01 BRA_205062740140_R01C01
                1051943                 1051943                 1051943
BRA_205096370081_R01C01 BRA_205096370081_R02C01 BRA_205096370081_R03C01
                1051943                 1051943                 1051943
BRA_205096370081_R04C01 BRA_205096370081_R05C01 BRA_205096370081_R06C01
                1051943                 1051943                 1051943
BRA_205096370081_R07C01 BRA_205096370081_R08C01 BRA_205096370104_R01C01
                1051943                 1051943                 1051943
BRA_205096370104_R02C01 BRA_205096370104_R03C01 BRA_205096370104_R04C01
                1051943                 1051943                 1051943
BRA_205096370104_R05C01 BRA_205096370104_R06C01 BRA_205096370104_R07C01
                1051943                 1051943                 1051943
BRA_205096370104_R08C01 BRA_205134980005_R01C01 BRA_205134980005_R02C01
                1051943                 1051943                 1051943
8  surrogate variables explain  95.37677 % of
    data variation

In [7]:
celltype = estimateCellProp(userdata=rgSet,
         refdata="FlowSorted.DLPFC.450k",
         nonnegative = TRUE, normalize=TRUE)

In [8]:
# Merge celltypes
celltype$name = celltype$Sample_Name
pheno = merge(mf, celltype, by = c('name'))
pheno = merge(pheno, sva, by = c('name'))

In [9]:
# First estimate Betas
beta = getB(mdat)

In [10]:
# Subsetting samples to those that pass QC
pheno_sub = pheno[pheno$Sample_Name %in% colnames(beta),]

In [11]:
# Estimate clocks using methylCIPHER
# Need to transpose the matrix, samples in columns and cpg in rows
beta = as.data.frame(t(beta))
pheno_sub = calcCoreClocks(beta, pheno_sub)

Please remember to cite the core Clocks you have used! Please refer to the README.md file for assistance.

In [19]:
prcPhenoAge::
clockOptions()

 [1] "calcAlcoholMcCartney"            "calcBMIMcCartney"
 [3] "calcBocklandt"                   "calcBohlin"
 [5] "calcClockCategory"               "calcDNAmClockCortical"
 [7] "calcDNAmTL"                      "calcDunedinPoAm38"
 [9] "calcEpiTOC"                      "calcEpiTOC2"
[11] "calcGaragnani"                   "calcHannum"
[13] "calcHorvath1"                    "calcHorvath2"
[15] "calcHRSInChPhenoAge"             "calcHypoClock"
[17] "calcKnight"                      "calcLeeControl"
[19] "calcLeeRefinedRobust"            "calcLeeRobust"
[21] "calcLin"                         "calcMayne"
[23] "calcMiAge"                       "calcPEDBE"
[25] "calcPhenoAge"                    "calcSmokingMcCartney"
[27] "calcVidalBralo"                  "calcWeidner"
[29] "calcZhang"                       "calcZhang2019"
[31] "prcPhenoAge::calcPRCPhenoAge"    "prcPhenoAge::calcnonPRCPhenoAge"
[33] "DunedinPoAm38::PoAmProjector"

In [25]:
# Estimate Zhang
userClocks = c("calcZhang2019")
pheno_sub = calcUserClocks(userClocks, beta, pheno_sub, imputation = FALSE)

In [26]:
# Preparing data for stochastic clock
beta_m = as.matrix(t(beta))
age = as.vector(pheno_sub$Age)
dim(beta_m)
dim(age)
head(colnames(beta_m))  # Should be sample IDs

[1] 821117    114

NULL

[1] "BRA_201465920012_R01C01" "BRA_201465920012_R02C01"
[3] "BRA_201465920012_R03C01" "BRA_201465920012_R04C01"
[5] "BRA_201465920012_R05C01" "BRA_201465920012_R06C01"

In [27]:
# Running stocastic clocks
clockpath = "/vast/palmer/scratch/montalvo-ortiz/jjm262/00tclocks/00uthealth/03scripts/01epigenome/glmStocALL.Rd"

# This is the function for stochastic clocks
RunStochClocks <- function(data.m,ages.v=NULL,refM.m=NULL){
 load(clockpath); ## load in stochastic clock information
 estF.m <- NULL;
 if(!is.null(refM.m)){
   estF.m <- epidish(data.m,ref=refM.m,method="RPC",maxit=500)$est;
 }
 predMage.lv <- list();
 eaa.lv <- list();
 iaa.lv <- list();
 for(c in 1:length(glmStocALL.lo)){
  glm.o <- glmStocALL.lo[[c]];
  coef.m <- coef(glm.o);
  intC <- coef.m[1,ncol(coef.m)]; ### intercept term
  coef.v <- coef.m[-1,ncol(coef.m)]; ### estimated regression coefficients
  commonCpGs.v <- intersect(names(coef.v),rownames(data.m));
  rep.idx <- match(commonCpGs.v,names(coef.v));
  map.idx <- match(commonCpGs.v,rownames(data.m));
  predMage.lv[[c]] <- as.vector(intC + matrix(coef.v[rep.idx],nrow=1) %*% data.m[map.idx,]);
  if(!is.null(ages.v)){
     eaa.lv[[c]] <- lm(predMage.lv[[c]] ~ ages.v)$res;     
     if(!is.null(refM.m)){
      iaa.lv[[c]] <- lm(predMage.lv[[c]] ~ ages.v + estF.m)$res;
     }
  }
 }
 return(list(mage=predMage.lv,eaa=eaa.lv,iaa=iaa.lv,estF=estF.m));
}

# Running function
sclocks = RunStochClocks(beta_m, age)

In [28]:
# Add sample IDs first (these are the column names of beta)
sample_ids <- colnames(beta_m)

mage_df <- as.data.frame(do.call(cbind, sclocks$mage))
colnames(mage_df) <- paste0("StochClock", seq_along(sclocks$mage))
mage_df$name <- sample_ids

eaa_df <- as.data.frame(do.call(cbind, sclocks$eaa))
colnames(eaa_df) <- paste0("EAA_StochClock", seq_along(sclocks$eaa))
eaa_df$name <- sample_ids

# Merge side by side by 'name'
combined_df <- merge(mage_df, eaa_df, by = "name")
combined_df
pheno_sub = merge(pheno_sub, combined_df, by = c('name'))
pheno_sub

    name                    StochClock1 StochClock2  StochClock3
1   BRA_201465920012_R01C01 21.84555      4.513590   38.72373
2   BRA_201465920012_R02C01 17.80645      7.576214   45.29077
3   BRA_201465920012_R03C01 29.46791      1.795859   39.73101
4   BRA_201465920012_R04C01 16.31163      2.873425   45.25659
5   BRA_201465920012_R05C01 26.86126      3.694324   42.52529
6   BRA_201465920012_R06C01 17.75092      9.953468   46.16633
7   BRA_201465920012_R08C01 17.14162      8.469922   40.10796
8   BRA_201465920048_R01C01 28.24137      8.600238   36.47719
9   BRA_201465920048_R02C01 36.17728     26.616832   43.90820
10  BRA_201465920048_R03C01 34.56808     13.911975   43.20531
11  BRA_201465920048_R04C01 22.06732     15.799985   44.90300
12  BRA_201465920048_R05C01 11.03315    -13.587002   38.89937
13  BRA_201465920048_R06C01 24.79615     19.019247   43.01226
14  BRA_201465920048_R07C01 20.94538      3.842814   33.90269
15  BRA_201465920048_R08C01 27.89736     15.768064   49.59199
16  BRA_201532190145_R01C01 18.51666      2.198469   43.09991
17  BRA_201532190145_R02C01 34.17628     29.432692   45.30524
18  BRA_201532190145_R03C01 23.72471     18.916332   46.42262
19  BRA_201532190145_R04C01 22.03480     22.877660   49.00197
20  BRA_201532190145_R05C01 16.98396      9.875848   45.34651
21  BRA_201532190145_R06C01 37.17771     34.993178   45.80636
22  BRA_201532190145_R08C01 18.12163    -15.548992   40.48513
23  BRA_202273260185_R01C01 26.95430     16.768775   51.08503
24  BRA_202273260185_R02C01 26.86435      1.485366   39.36469
25  BRA_202273260185_R03C01 21.05010     14.488600   46.98948
26  BRA_202273260185_R04C01 10.45610     -8.391377   41.51215
27  BRA_202273260185_R05C01 25.68568     13.467118   48.14104
28  BRA_202273260185_R06C01 13.62670    -11.456233   40.26024
29  BRA_202273260185_R07C01 22.95587     11.130196   41.79165
30  BRA_202273260185_R08C01 32.40067      9.790107   43.75431
⋮   ⋮                       ⋮           ⋮            ⋮
85  BRA_205062740052_R03C01 29.51006      6.20649267 44.56846
86  BRA_205062740052_R05C01 23.60574    -11.16889228 38.57514
87  BRA_205062740052_R06C01 36.60548     13.24369510 43.16304
88  BRA_205062740052_R07C01 26.58194     -0.02281981 44.91622
89  BRA_205062740052_R08C01 29.88676      9.46521323 48.85387
90  BRA_205062740070_R01C01 31.69441      7.83331729 44.53529
91  BRA_205062740070_R02C01 35.28620      2.92136972 46.52256
92  BRA_205062740070_R03C01 33.25454     11.80312795 44.14519
93  BRA_205062740070_R04C01 20.73654    -12.88104391 39.90960
94  BRA_205062740070_R05C01 20.85331    -13.76198767 41.86440
95  BRA_205062740070_R06C01 37.67107     15.79246440 45.31606
96  BRA_205062740070_R07C01 25.20110      2.82810754 43.28189
97  BRA_205062740070_R08C01 37.25331     11.53802780 40.60430
98  BRA_205062740140_R01C01 21.11819     -6.79026058 46.52831
99  BRA_205096370081_R01C01 30.30496     17.59138955 47.19033
100 BRA_205096370081_R02C01 21.44423      5.56875064 46.70131
101 BRA_205096370081_R03C01 32.32506     16.43892531 46.41015
102 BRA_205096370081_R04C01 29.55127      4.65732554 37.39332
103 BRA_205096370081_R05C01 23.77356     -0.27860942 44.37413
104 BRA_205096370081_R06C01 27.65224     -1.80534719 44.78127
105 BRA_205096370081_R07C01 35.42851     14.36824836 42.00159
106 BRA_205096370081_R08C01 24.66672     26.59934249 47.60594
107 BRA_205096370104_R01C01 34.11843     11.96248491 48.31235
108 BRA_205096370104_R02C01 27.05954     15.71993063 47.27033
109 BRA_205096370104_R03C01 15.66053    -14.85594932 38.89538
110 BRA_205096370104_R04C01 22.99109      1.30642419 45.81560
111 BRA_205096370104_R05C01 38.44926     19.87130289 46.61653
112 BRA_205096370104_R07C01 30.71411      1.35533133 42.77506
113 BRA_205134980005_R01C01 34.98453     15.49814493 42.14020
114 BRA_205134980005_R02C01 37.29443     14.66776443 42.28124
    EAA_StochClock1 EAA_StochClock2 EAA_StochClock3
1    -3.1664033     -0.9963250       -5.1253923
2    -2.7238284      9.4132725        2.2618458
3     1.0946989     -9.2242857       -4.7332627
4    -5.7125354      2.2614928        1.9542652
5     0.3554117     -4.2645822       -1.5972339
6   -10.2488188     -0.4544291        1.7704115
7    -3.7621331      9.6947330       -2.9893153
8     0.9885796     -0.5831638       -7.7820366
9     4.8162826     10.6987049       -1.1028696
10    5.4479178      1.6673345       -1.3956646
11    0.4166200     15.8003000        1.6690273
12   -4.6419756     -3.7907224       -3.2410022
13   -4.3240078      6.7746058       -1.5887111
14   -6.6808901     -5.9528354      -10.4248860
15   -2.3432179      1.6866800        4.7859727
16   -1.6401393      4.6477750        0.1393337
17   -0.1725058      8.6165826       -0.2526318
18   -2.7811330     10.9574259        2.3000966
19   -7.0853581     10.6330192        4.4010021
20  -11.3892498     -1.1442971        0.8822408
21    2.4554561     13.5648200        0.1801366
22    1.3260815     -7.5894553       -1.8602943
23   -1.0454392      6.3608772        6.6891106
24    0.7319773     -5.8612925       -4.6894803
25   -4.3353326      8.3664376        3.0720103
26   -8.5802853     -4.1053272       -1.2433790
27   -6.0487899     -3.0632569        3.0616149
28   -2.0484231     -1.6599528       -1.8801349
29   -3.9234491      2.5590422       -2.3992278
30    2.5335690     -3.6790292       -0.9833616
⋮   ⋮               ⋮               ⋮
85   5.61852349      2.53332097      0.9243813
86   6.43672162     -3.82160373     -3.8386329
87   5.99142868     -1.44993685     -1.7113290
88   3.43734642     -2.47149593      1.4088438
89   1.88701868     -0.94268418      4.4579446
90   1.45383386     -6.24806686     -0.2707311
91  10.64771668     -1.97629756      2.7417870
92  -1.09423836     -9.01298191     -1.4126845
93   3.94099187     -4.92150758     -2.4358253
94   3.68428769     -6.41469913     -0.5493785
95   2.94881370     -5.63589325     -0.3101630
96  -0.18432283     -3.29405533     -0.6355851
97   5.14536254     -5.60459531     -4.5434707
98   3.57570122     -0.05521982      4.0461799
99  -1.42951311      1.06101423      2.1109131
100  2.40784408      9.85480023      3.9457866
101 -0.15636177     -1.31594559      1.1940246
102  6.03320834      1.59640163     -6.1824053
103 -0.11797383     -3.95178112      0.7300561
104  1.89333550     -8.53975785      0.7954439
105  2.94709765     -3.38662254     -3.2145340
106 -6.69427452     10.68121496      2.5948693
107  3.13090269     -3.34339482      3.3696272
108  0.55368923      7.76102439      3.1478032
109 -0.01459438     -5.05966961     -3.2449935
110  0.59345025      0.08224366      2.4449209
111  5.59437008      1.50418420      1.3320608
112  5.70215740     -4.15458374     -1.0740606
113  1.75616324     -3.48122155     -3.2126220
114  4.81301372     -3.08710648     -2.9348828

    name                    SAB   Sentrix_ID          Year Ethnicity Gender Age
1   BRA_201465920012_R01C01 67917 201465920012_R01C01 2018 Hispanic  Male   44
2   BRA_201465920012_R02C01 67927 201465920012_R02C01 2018 Black     Female 32
3   BRA_201465920012_R03C01 67928 201465920012_R03C01 2018 Black     Male   53
4   BRA_201465920012_R04C01 67929 201465920012_R04C01 2018 White     Female 36
5   BRA_201465920012_R05C01 67930 201465920012_R05C01 2018 White     Male   48
6   BRA_201465920012_R06C01 67931 201465920012_R06C01 2018 White     Male   52
7   BRA_201465920012_R08C01 67943 201465920012_R08C01 2018 White     Male   33
8   BRA_201465920048_R01C01 67944 201465920048_R01C01 2018 White     Female 50
9   BRA_201465920048_R02C01 67945 201465920048_R02C01 2018 Black     Male   61
10  BRA_201465920048_R03C01 67933 201465920048_R03C01 2018 White     Female 55
11  BRA_201465920048_R04C01 67935 201465920048_R04C01 2018 White     Male   35
12  BRA_201465920048_R05C01 67938 201465920048_R05C01 2018 Black     Male   19
13  BRA_201465920048_R06C01 67940 201465920048_R06C01 2018 White     Male   55
14  BRA_201465920048_R07C01 67946 201465920048_R07C01 2018 White     Male   51
15  BRA_201465920048_R08C01 67948 201465920048_R08C01 2018 Hispanic  Male   58
16  BRA_201532190145_R01C01 67974 201532190145_R01C01 2018 White     Female 31
17  BRA_201532190145_R02C01 67976 201532190145_R02C01 2018 White     Female 69
18  BRA_201532190145_R03C01 67977 201532190145_R03C01 2018 White     Female 48
19  BRA_201532190145_R04C01 67978 201532190145_R04C01 2018 White     Female 55
20  BRA_201532190145_R05C01 67979 201532190145_R05C01 2018 White     Female 53
21  BRA_201532190145_R06C01 67980 201532190145_R06C01 2018 White     Female 70
22  BRA_201532190145_R08C01 67915 201532190145_R08C01 2018 White     Male   22
23  BRA_202273260185_R01C01 67926 202273260185_R01C01 2018 Hispanic  Male   52
24  BRA_202273260185_R02C01 67937 202273260185_R02C01 2018 White     Male   47
25  BRA_202273260185_R03C01 67968 202273260185_R03C01 2018 Black     Female 45
26  BRA_202273260185_R04C01 67969 202273260185_R04C01 2018 Black     Male   28
27  BRA_202273260185_R05C01 67970 202273260185_R05C01 2018 White     Male   62
28  BRA_202273260185_R06C01 67971 202273260185_R06C01 2018 Black     Male   19
29  BRA_202273260185_R07C01 67972 202273260185_R07C01 2018 Black     Male   49
30  BRA_202273260185_R08C01 67973 202273260185_R08C01 2018 Black     Male   57
⋮   ⋮                       ⋮     ⋮                   ⋮    ⋮         ⋮      ⋮
85  BRA_205062740052_R03C01 79219 205062740052_R03C01 2022 White     Male   41
86  BRA_205062740052_R05C01 79223 205062740052_R05C01 2022 White     Male   23
87  BRA_205062740052_R06C01 67994 205062740052_R06C01 2022 Hispanic  Male   59
88  BRA_205062740052_R07C01 67982 205062740052_R07C01 2022 White     Male   39
89  BRA_205062740052_R08C01 67990 205062740052_R08C01 2022 White     Male   52
90  BRA_205062740070_R01C01 79220 205062740070_R01C01 2022 White     Male   58
91  BRA_205062740070_R02C01 67985 205062740070_R02C01 2022 White     Male   43
92  BRA_205062740070_R03C01 79225 205062740070_R03C01 2022 Black     Female 69
93  BRA_205062740070_R04C01 79218 205062740070_R04C01 2022 Black     Male   22
94  BRA_205062740070_R05C01 79200 205062740070_R05C01 2022 White     Male   23
95  BRA_205062740070_R06C01 79213 205062740070_R06C01 2022 Black     Male   70
96  BRA_205062740070_R07C01 79209 205062740070_R07C01 2022 White     Male   45
97  BRA_205062740070_R08C01 79205 205062740070_R08C01 2022 White     Male   63
98  BRA_205062740140_R01C01 67983 205062740140_R01C01 2022 White     Female 24
99  BRA_205096370081_R01C01 79214 205096370081_R01C01 2022 White     Male   62
100 BRA_205096370081_R02C01 79229 205096370081_R02C01 2022 Black     Male   28
101 BRA_205096370081_R03C01 67999 205096370081_R03C01 2022 White     Male   64
102 BRA_205096370081_R04C01 79228 205096370081_R04C01 2022 White     Male   40
103 BRA_205096370081_R05C01 79226 205096370081_R05C01 2022 Black     Female 41
104 BRA_205096370081_R06C01 79230 205096370081_R06C01 2022 Black     Female 46
105 BRA_205096370081_R07C01 67992 205096370081_R07C01 2022 Black     Female 64
106 BRA_205096370081_R08C01 67997 205096370081_R08C01 2022 Hispanic  Male   61
107 BRA_205096370104_R01C01 79221 205096370104_R01C01 2022 Black     Female 60
108 BRA_205096370104_R02C01 79216 205096370104_R02C01 2022 White     Male   48
109 BRA_205096370104_R03C01 79217 205096370104_R03C01 2022 Hispanic  Male   19
110 BRA_205096370104_R04C01 67984 205096370104_R04C01 2022 White     Male   37
111 BRA_205096370104_R05C01 79212 205096370104_R05C01 2022 Black     Female 65
112 BRA_205096370104_R07C01 79215 205096370104_R07C01 2022 Hispanic  Male   44
113 BRA_205134980005_R01C01 79238 205134980005_R01C01 2022 Black     Female 66
114 BRA_205134980005_R02C01 79239 205134980005_R02C01 2022 Black     Male   64
    PMIhrs pH
1   32.67  5.91
2   31.57  6.56
3   28.65  6.79
4   28.20  6.80
5   31.30  6.44
6   31.92  6.38
7   10.57  6.72
8    9.55  6.63
9   37.40  6.64
10  28.78  7.02
11  18.20  6.20
12  36.03  6.63
13  23.75  5.84
14  22.98  6.73
15  26.48  6.82
16  23.60  6.56
17  24.82  6.42
18  31.97  6.73
19  27.62  6.40
20  30.15  6.89
21  28.60  6.57
22  53.82  6.63
23  47.92  6.49
24  27.62  6.23
25  13.07  6.49
26  23.97  6.68
27  23.82  7.29
28  21.60  7.05
29  28.22  7.03
30  19.92  6.35
⋮   ⋮      ⋮
85  29.32    NA
86  21.08    NA
87  32.35  6.80
88  16.52  6.53
89  23.43  6.77
90  15.05    NA
91  25.17  6.44
92  20.32    NA
93  22.10    NA
94  16.78  6.52
95  27.32    NA
96  20.63    NA
97  14.55    NA
98  14.50  6.50
99  24.28    NA
100 39.83    NA
101 43.33  6.53
102 33.48    NA
103 38.70    NA
104 12.32    NA
105 28.03  6.62
106 26.38  6.89
107 23.80    NA
108 13.17    NA
109 28.88    NA
110 11.73  6.04
111 19.25    NA
112 56.92    NA
113 23.83    NA
114 44.73    NA
    Cause_of_Death
1   acute carisoprodol toxicity
2   undetermined
3   acute toxicity of cocaine and ethanol
4   toxic effects of methadone
5   GSW
6   cardiovascular disease, not opioid
7   multi overdose: benzodiazepine, amphetamine, cocaine, EtOH, and opioid
8   sepsis
9   Cardiovascular disease
10  carciovascular disease
11  combined toxicity of heroin, methamphetamine, alprazolam and ethanol
12  combined toxic effects of alprazolam, codeine and morphine
13  Cardiovascular disease
14  cocaine and opioid OD
15  Cardiovascular disease
16  opioid, amitriptyline, diphenhydramine, hydroxyzine, promethazine, and benzo OD
17  Cardiovascular disease
18  prescription medication OD
19  opioid, EtOH, benzodiazepine, diphenhydramine and gabapentin OD
20  alcohol and diphenhydramine OD
21  fall
22  Toxic effects of U-47700
23  Cardiovascular disease
24  Cardiovascular disease
25  toxic effect of cocaine
26  cirrhosis and ESRD
27  Cardiovascular disease with signs of chronic alcoholism (hepatic fibrosis)
28  GSW
29  cocaine OD
30  perforated ulcer with sepsis
⋮   ⋮
85  Cocaine and oxycodone toxicity
86  Combined toxic effects of fentanyl, cocaine, alprazolam, and amphetamine
87  Cardiovascular disease
88  Cardiovascular disease
89  Cardiovascular disease
90  Acute and chronic ethanolism with toxic effects of chlordiazepoxide
91  toxic effects of methamphetamine
92  Atherosclerotic and hypertensive cardiovascular disease
93  Combined alprazolam, etizolam, and fentanyl toxicities
94  mitragynine, benzodiazepine, and loperamide OD
95  Pulmonary thromboembolism due to deep vein thromboses of lower extremities
96  Acute toxicity due to the combined effects of fentanyl, midazolam, diphenhydramine, amphetamine, and bupropion
97  Suicide due to combined acetaminophen, hydrocodone, zolpidem toxicity
98  opioid, benzodiazepine and SSRI OD
99  Acute Methamphetamine Toxicity
100 Complications of morbid obesity and asthma
101 Cardiovascular disease
102 Combined toxic effects of fentanyl, alprazolam, methamphetamine, and MDMA
103 hypertensive and atherosclerotic cardiovascular disease
104 Toxic effects of fentanyl, codeine, hydrocodone, quetiapine, and diphenhydramine
105 Cardiovascular disease
106 Cardiovascular disease
107 Acute cocaine toxicity
108 Combined toxic effects of heroin, methamphetmine, mitragynine and ethanol
109 Toxic effects of fentanyl, alprazolam, and tramadol
110 diabetic ketoacidosis
111 Suicide due to toxic effects of cyclobenzaprine with diazepam
112 Bilateral pulmonary thromboemboli due to deep vein thrombosis associated with obesity
113
114
    ⋯ Horvath1 PhenoAge   epiTOC2     Zhang2019 StochClock1 StochClock2
1   ⋯ 39.30907 -22.791375  181.13486  30.09624  21.84555      4.513590
2   ⋯ 39.53668 -17.402457   62.77680  25.51929  17.80645      7.576214
3   ⋯ 46.63943 -20.579133  369.31879  33.18496  29.46791      1.795859
4   ⋯ 34.85467 -20.439521  901.55171  30.34616  16.31163      2.873425
5   ⋯ 43.41878 -30.526159  946.82365  40.70224  26.86126      3.694324
6   ⋯ 51.33423 -21.974027  917.82742  41.69750  17.75092      9.953468
7   ⋯ 36.35575 -20.421391  456.39942  24.81313  17.14162      8.469922
8   ⋯ 50.16851 -22.062699  838.08977  37.18442  28.24137      8.600238
9   ⋯ 63.10395  -9.884480 1429.80421  43.36969  36.17728     26.616832
10  ⋯ 58.03117 -11.649303  302.05967  43.70871  34.56808     13.911975
11  ⋯ 36.93136 -22.473605 1245.13714  29.48804  22.06732     15.799985
12  ⋯ 26.64180 -35.508236  549.73552  10.20407  11.03315    -13.587002
13  ⋯ 46.89897 -16.660257  228.43806  39.32562  24.79615     19.019247
14  ⋯ 56.47985 -15.829706 1471.07436  31.16354  20.94538      3.842814
15  ⋯ 53.80804  -5.440468 1359.81792  42.13414  27.89736     15.768064
16  ⋯ 35.70493 -16.030792  126.77464  24.08520  18.51666      2.198469
17  ⋯ 58.95733 -13.206898  300.12386  49.73528  34.17628     29.432692
18  ⋯ 49.38695  -2.559894  266.56489  38.41806  23.72471     18.916332
19  ⋯ 49.96347  -9.109668  556.14810  39.70604  22.03480     22.877660
20  ⋯ 46.41276 -18.500426  587.93628  36.66341  16.98396      9.875848
21  ⋯ 60.05197  -3.076856  367.45426  50.50771  37.17771     34.993178
22  ⋯ 20.44530 -30.495376  144.04545  11.03668  18.12163    -15.548992
23  ⋯ 44.95381 -11.679638   91.47075  38.03520  26.95430     16.768775
24  ⋯ 47.93302 -20.958274  568.51908  30.81018  26.86435      1.485366
25  ⋯ 47.47567  -7.207249 1008.95471  36.77153  21.05010     14.488600
26  ⋯ 29.88865 -30.681731  744.08335  15.10747  10.45610     -8.391377
27  ⋯ 52.43628 -12.987345   79.13760  37.89707  25.68568     13.467118
28  ⋯ 32.81855 -22.434213 1272.32810  10.53949  13.62670    -11.456233
29  ⋯ 44.21166 -11.506854  182.32383  32.51449  22.95587     11.130196
30  ⋯ 51.41306 -11.845773  353.77275  39.31593  32.40067      9.790107
⋮   ⋱ ⋮        ⋮          ⋮           ⋮         ⋮           ⋮
85  ⋯ 48.46075 -19.084346   74.749236 34.48763  29.51006      6.20649267
86  ⋯ 33.01828 -25.279530 -112.057087 20.29733  23.60574    -11.16889228
87  ⋯ 61.56525 -17.791800  -11.011478 44.81230  36.60548     13.24369510
88  ⋯ 42.59565 -23.565363  128.749012 29.25634  26.58194     -0.02281981
89  ⋯ 50.38813 -18.147567  102.784481 35.31320  29.88676      9.46521323
90  ⋯ 54.72550 -16.793087   29.845747 41.68040  31.69441      7.83331729
91  ⋯ 48.25436 -21.911102   14.049244 35.74688  35.28620      2.92136972
92  ⋯ 55.94222  -8.547048  127.054806 42.59401  33.25454     11.80312795
93  ⋯ 38.68370 -25.892587 -137.760859 19.15241  20.73654    -12.88104391
94  ⋯ 30.70730 -32.507123   79.628406 17.93872  20.85331    -13.76198767
95  ⋯ 59.70852 -12.054344  190.485481 44.10332  37.67107     15.79246440
96  ⋯ 46.63121 -24.337030    2.221868 34.33469  25.20110      2.82810754
97  ⋯ 61.13019  -8.308135  469.576519 42.31494  37.25331     11.53802780
98  ⋯ 31.61695 -25.652079 -123.191876 20.31298  21.11819     -6.79026058
99  ⋯ 52.20219 -10.739224   91.565446 44.82558  30.30496     17.59138955
100 ⋯ 35.26329 -14.616435  -47.912604 25.23492  21.44423      5.56875064
101 ⋯ 58.92430 -14.493979   41.540822 44.45844  32.32506     16.43892531
102 ⋯ 44.96950 -19.752064  -98.908492 34.52192  29.55127      4.65732554
103 ⋯ 41.63770 -23.197600  -67.869464 32.61099  23.77356     -0.27860942
104 ⋯ 62.76821 -20.553331  177.438061 36.12474  27.65224     -1.80534719
105 ⋯ 56.94648 -18.390741    1.288358 42.16441  35.42851     14.36824836
106 ⋯ 52.84985  -9.858009   59.736717 42.14603  24.66672     26.59934249
107 ⋯ 58.25992  -8.365389  -24.275479 45.17278  34.11843     11.96248491
108 ⋯ 49.85275 -19.398138  109.750446 39.91151  27.05954     15.71993063
109 ⋯ 24.59350 -33.398048 -119.098948 16.45387  15.66053    -14.85594932
110 ⋯ 42.24281 -22.832184  -38.586821 31.98092  22.99109      1.30642419
111 ⋯ 57.88040  -9.150546  -60.968314 45.08153  38.44926     19.87130289
112 ⋯ 45.31123 -20.754439  -41.454759 33.98189  30.71411      1.35533133
113 ⋯ 57.36760 -18.303709  -12.229472 45.82237  34.98453     15.49814493
114 ⋯ 53.39972  -9.649889  173.512101 43.99944  37.29443     14.66776443
    StochClock3 EAA_StochClock1 EAA_StochClock2 EAA_StochClock3
1   38.72373     -3.1664033     -0.9963250       -5.1253923
2   45.29077     -2.7238284      9.4132725        2.2618458
3   39.73101      1.0946989     -9.2242857       -4.7332627
4   45.25659     -5.7125354      2.2614928        1.9542652
5   42.52529      0.3554117     -4.2645822       -1.5972339
6   46.16633    -10.2488188     -0.4544291        1.7704115
7   40.10796     -3.7621331      9.6947330       -2.9893153
8   36.47719      0.9885796     -0.5831638       -7.7820366
9   43.90820      4.8162826     10.6987049       -1.1028696
10  43.20531      5.4479178      1.6673345       -1.3956646
11  44.90300      0.4166200     15.8003000        1.6690273
12  38.89937     -4.6419756     -3.7907224       -3.2410022
13  43.01226     -4.3240078      6.7746058       -1.5887111
14  33.90269     -6.6808901     -5.9528354      -10.4248860
15  49.59199     -2.3432179      1.6866800        4.7859727
16  43.09991     -1.6401393      4.6477750        0.1393337
17  45.30524     -0.1725058      8.6165826       -0.2526318
18  46.42262     -2.7811330     10.9574259        2.3000966
19  49.00197     -7.0853581     10.6330192        4.4010021
20  45.34651    -11.3892498     -1.1442971        0.8822408
21  45.80636      2.4554561     13.5648200        0.1801366
22  40.48513      1.3260815     -7.5894553       -1.8602943
23  51.08503     -1.0454392      6.3608772        6.6891106
24  39.36469      0.7319773     -5.8612925       -4.6894803
25  46.98948     -4.3353326      8.3664376        3.0720103
26  41.51215     -8.5802853     -4.1053272       -1.2433790
27  48.14104     -6.0487899     -3.0632569        3.0616149
28  40.26024     -2.0484231     -1.6599528       -1.8801349
29  41.79165     -3.9234491      2.5590422       -2.3992278
30  43.75431      2.5335690     -3.6790292       -0.9833616
⋮   ⋮           ⋮               ⋮               ⋮
85  44.56846     5.61852349      2.53332097      0.9243813
86  38.57514     6.43672162     -3.82160373     -3.8386329
87  43.16304     5.99142868     -1.44993685     -1.7113290
88  44.91622     3.43734642     -2.47149593      1.4088438
89  48.85387     1.88701868     -0.94268418      4.4579446
90  44.53529     1.45383386     -6.24806686     -0.2707311
91  46.52256    10.64771668     -1.97629756      2.7417870
92  44.14519    -1.09423836     -9.01298191     -1.4126845
93  39.90960     3.94099187     -4.92150758     -2.4358253
94  41.86440     3.68428769     -6.41469913     -0.5493785
95  45.31606     2.94881370     -5.63589325     -0.3101630
96  43.28189    -0.18432283     -3.29405533     -0.6355851
97  40.60430     5.14536254     -5.60459531     -4.5434707
98  46.52831     3.57570122     -0.05521982      4.0461799
99  47.19033    -1.42951311      1.06101423      2.1109131
100 46.70131     2.40784408      9.85480023      3.9457866
101 46.41015    -0.15636177     -1.31594559      1.1940246
102 37.39332     6.03320834      1.59640163     -6.1824053
103 44.37413    -0.11797383     -3.95178112      0.7300561
104 44.78127     1.89333550     -8.53975785      0.7954439
105 42.00159     2.94709765     -3.38662254     -3.2145340
106 47.60594    -6.69427452     10.68121496      2.5948693
107 48.31235     3.13090269     -3.34339482      3.3696272
108 47.27033     0.55368923      7.76102439      3.1478032
109 38.89538    -0.01459438     -5.05966961     -3.2449935
110 45.81560     0.59345025      0.08224366      2.4449209
111 46.61653     5.59437008      1.50418420      1.3320608
112 42.77506     5.70215740     -4.15458374     -1.0740606
113 42.14020     1.75616324     -3.48122155     -3.2126220
114 42.28124     4.81301372     -3.08710648     -2.9348828

In [29]:
# Save specific objects to an RData file
save(beta, qc, pheno, pheno_sub, rgSet, file = "/vast/palmer/scratch/montalvo-ortiz/jjm262/00tclocks/00uthealth/00databases/05epigenome/00uthealth_brain-08022025.RData")

In [30]:
# Save specific objects to an RData file
saveRDS(pheno_sub, file = "/vast/palmer/scratch/montalvo-ortiz/jjm262/00tclocks/00uthealth/00databases/05epigenome/00uthealth_brain-08022025.rds")

In [31]:
# Modification made on 08032025
load("/vast/palmer/scratch/montalvo-ortiz/jjm262/00tclocks/00uthealth/00databases/05epigenome/00uthealth_brain-08022025.RData")

In [32]:
# Estimate cortical clock
cortical_age <- methyAge(t(beta), clock='ShirebyG2020')

Warning message in methyAge(t(beta), clock = "ShirebyG2020"):
“Found  6 out of 348 probes missing! They will be assigned with mean values from reference dataset, missing probes are:
  cg00771642 cg09372546 cg10904972 cg22285878 cg24346776 cg24420164”

In [33]:
# Change colnames
colnames(cortical_age) = c("name", "corticalClock")
# Merge
pheno_sub = merge(pheno_sub, cortical_age, by = c('name'))
pheno_sub

    name                    SAB   Sentrix_ID          Year Ethnicity Gender Age
1   BRA_201465920012_R01C01 67917 201465920012_R01C01 2018 Hispanic  Male   44
2   BRA_201465920012_R02C01 67927 201465920012_R02C01 2018 Black     Female 32
3   BRA_201465920012_R03C01 67928 201465920012_R03C01 2018 Black     Male   53
4   BRA_201465920012_R04C01 67929 201465920012_R04C01 2018 White     Female 36
5   BRA_201465920012_R05C01 67930 201465920012_R05C01 2018 White     Male   48
6   BRA_201465920012_R06C01 67931 201465920012_R06C01 2018 White     Male   52
7   BRA_201465920012_R08C01 67943 201465920012_R08C01 2018 White     Male   33
8   BRA_201465920048_R01C01 67944 201465920048_R01C01 2018 White     Female 50
9   BRA_201465920048_R02C01 67945 201465920048_R02C01 2018 Black     Male   61
10  BRA_201465920048_R03C01 67933 201465920048_R03C01 2018 White     Female 55
11  BRA_201465920048_R04C01 67935 201465920048_R04C01 2018 White     Male   35
12  BRA_201465920048_R05C01 67938 201465920048_R05C01 2018 Black     Male   19
13  BRA_201465920048_R06C01 67940 201465920048_R06C01 2018 White     Male   55
14  BRA_201465920048_R07C01 67946 201465920048_R07C01 2018 White     Male   51
15  BRA_201465920048_R08C01 67948 201465920048_R08C01 2018 Hispanic  Male   58
16  BRA_201532190145_R01C01 67974 201532190145_R01C01 2018 White     Female 31
17  BRA_201532190145_R02C01 67976 201532190145_R02C01 2018 White     Female 69
18  BRA_201532190145_R03C01 67977 201532190145_R03C01 2018 White     Female 48
19  BRA_201532190145_R04C01 67978 201532190145_R04C01 2018 White     Female 55
20  BRA_201532190145_R05C01 67979 201532190145_R05C01 2018 White     Female 53
21  BRA_201532190145_R06C01 67980 201532190145_R06C01 2018 White     Female 70
22  BRA_201532190145_R08C01 67915 201532190145_R08C01 2018 White     Male   22
23  BRA_202273260185_R01C01 67926 202273260185_R01C01 2018 Hispanic  Male   52
24  BRA_202273260185_R02C01 67937 202273260185_R02C01 2018 White     Male   47
25  BRA_202273260185_R03C01 67968 202273260185_R03C01 2018 Black     Female 45
26  BRA_202273260185_R04C01 67969 202273260185_R04C01 2018 Black     Male   28
27  BRA_202273260185_R05C01 67970 202273260185_R05C01 2018 White     Male   62
28  BRA_202273260185_R06C01 67971 202273260185_R06C01 2018 Black     Male   19
29  BRA_202273260185_R07C01 67972 202273260185_R07C01 2018 Black     Male   49
30  BRA_202273260185_R08C01 67973 202273260185_R08C01 2018 Black     Male   57
⋮   ⋮                       ⋮     ⋮                   ⋮    ⋮         ⋮      ⋮
85  BRA_205062740052_R03C01 79219 205062740052_R03C01 2022 White     Male   41
86  BRA_205062740052_R05C01 79223 205062740052_R05C01 2022 White     Male   23
87  BRA_205062740052_R06C01 67994 205062740052_R06C01 2022 Hispanic  Male   59
88  BRA_205062740052_R07C01 67982 205062740052_R07C01 2022 White     Male   39
89  BRA_205062740052_R08C01 67990 205062740052_R08C01 2022 White     Male   52
90  BRA_205062740070_R01C01 79220 205062740070_R01C01 2022 White     Male   58
91  BRA_205062740070_R02C01 67985 205062740070_R02C01 2022 White     Male   43
92  BRA_205062740070_R03C01 79225 205062740070_R03C01 2022 Black     Female 69
93  BRA_205062740070_R04C01 79218 205062740070_R04C01 2022 Black     Male   22
94  BRA_205062740070_R05C01 79200 205062740070_R05C01 2022 White     Male   23
95  BRA_205062740070_R06C01 79213 205062740070_R06C01 2022 Black     Male   70
96  BRA_205062740070_R07C01 79209 205062740070_R07C01 2022 White     Male   45
97  BRA_205062740070_R08C01 79205 205062740070_R08C01 2022 White     Male   63
98  BRA_205062740140_R01C01 67983 205062740140_R01C01 2022 White     Female 24
99  BRA_205096370081_R01C01 79214 205096370081_R01C01 2022 White     Male   62
100 BRA_205096370081_R02C01 79229 205096370081_R02C01 2022 Black     Male   28
101 BRA_205096370081_R03C01 67999 205096370081_R03C01 2022 White     Male   64
102 BRA_205096370081_R04C01 79228 205096370081_R04C01 2022 White     Male   40
103 BRA_205096370081_R05C01 79226 205096370081_R05C01 2022 Black     Female 41
104 BRA_205096370081_R06C01 79230 205096370081_R06C01 2022 Black     Female 46
105 BRA_205096370081_R07C01 67992 205096370081_R07C01 2022 Black     Female 64
106 BRA_205096370081_R08C01 67997 205096370081_R08C01 2022 Hispanic  Male   61
107 BRA_205096370104_R01C01 79221 205096370104_R01C01 2022 Black     Female 60
108 BRA_205096370104_R02C01 79216 205096370104_R02C01 2022 White     Male   48
109 BRA_205096370104_R03C01 79217 205096370104_R03C01 2022 Hispanic  Male   19
110 BRA_205096370104_R04C01 67984 205096370104_R04C01 2022 White     Male   37
111 BRA_205096370104_R05C01 79212 205096370104_R05C01 2022 Black     Female 65
112 BRA_205096370104_R07C01 79215 205096370104_R07C01 2022 Hispanic  Male   44
113 BRA_205134980005_R01C01 79238 205134980005_R01C01 2022 Black     Female 66
114 BRA_205134980005_R02C01 79239 205134980005_R02C01 2022 Black     Male   64
    PMIhrs pH
1   32.67  5.91
2   31.57  6.56
3   28.65  6.79
4   28.20  6.80
5   31.30  6.44
6   31.92  6.38
7   10.57  6.72
8    9.55  6.63
9   37.40  6.64
10  28.78  7.02
11  18.20  6.20
12  36.03  6.63
13  23.75  5.84
14  22.98  6.73
15  26.48  6.82
16  23.60  6.56
17  24.82  6.42
18  31.97  6.73
19  27.62  6.40
20  30.15  6.89
21  28.60  6.57
22  53.82  6.63
23  47.92  6.49
24  27.62  6.23
25  13.07  6.49
26  23.97  6.68
27  23.82  7.29
28  21.60  7.05
29  28.22  7.03
30  19.92  6.35
⋮   ⋮      ⋮
85  29.32    NA
86  21.08    NA
87  32.35  6.80
88  16.52  6.53
89  23.43  6.77
90  15.05    NA
91  25.17  6.44
92  20.32    NA
93  22.10    NA
94  16.78  6.52
95  27.32    NA
96  20.63    NA
97  14.55    NA
98  14.50  6.50
99  24.28    NA
100 39.83    NA
101 43.33  6.53
102 33.48    NA
103 38.70    NA
104 12.32    NA
105 28.03  6.62
106 26.38  6.89
107 23.80    NA
108 13.17    NA
109 28.88    NA
110 11.73  6.04
111 19.25    NA
112 56.92    NA
113 23.83    NA
114 44.73    NA
    Cause_of_Death
1   acute carisoprodol toxicity
2   undetermined
3   acute toxicity of cocaine and ethanol
4   toxic effects of methadone
5   GSW
6   cardiovascular disease, not opioid
7   multi overdose: benzodiazepine, amphetamine, cocaine, EtOH, and opioid
8   sepsis
9   Cardiovascular disease
10  carciovascular disease
11  combined toxicity of heroin, methamphetamine, alprazolam and ethanol
12  combined toxic effects of alprazolam, codeine and morphine
13  Cardiovascular disease
14  cocaine and opioid OD
15  Cardiovascular disease
16  opioid, amitriptyline, diphenhydramine, hydroxyzine, promethazine, and benzo OD
17  Cardiovascular disease
18  prescription medication OD
19  opioid, EtOH, benzodiazepine, diphenhydramine and gabapentin OD
20  alcohol and diphenhydramine OD
21  fall
22  Toxic effects of U-47700
23  Cardiovascular disease
24  Cardiovascular disease
25  toxic effect of cocaine
26  cirrhosis and ESRD
27  Cardiovascular disease with signs of chronic alcoholism (hepatic fibrosis)
28  GSW
29  cocaine OD
30  perforated ulcer with sepsis
⋮   ⋮
85  Cocaine and oxycodone toxicity
86  Combined toxic effects of fentanyl, cocaine, alprazolam, and amphetamine
87  Cardiovascular disease
88  Cardiovascular disease
89  Cardiovascular disease
90  Acute and chronic ethanolism with toxic effects of chlordiazepoxide
91  toxic effects of methamphetamine
92  Atherosclerotic and hypertensive cardiovascular disease
93  Combined alprazolam, etizolam, and fentanyl toxicities
94  mitragynine, benzodiazepine, and loperamide OD
95  Pulmonary thromboembolism due to deep vein thromboses of lower extremities
96  Acute toxicity due to the combined effects of fentanyl, midazolam, diphenhydramine, amphetamine, and bupropion
97  Suicide due to combined acetaminophen, hydrocodone, zolpidem toxicity
98  opioid, benzodiazepine and SSRI OD
99  Acute Methamphetamine Toxicity
100 Complications of morbid obesity and asthma
101 Cardiovascular disease
102 Combined toxic effects of fentanyl, alprazolam, methamphetamine, and MDMA
103 hypertensive and atherosclerotic cardiovascular disease
104 Toxic effects of fentanyl, codeine, hydrocodone, quetiapine, and diphenhydramine
105 Cardiovascular disease
106 Cardiovascular disease
107 Acute cocaine toxicity
108 Combined toxic effects of heroin, methamphetmine, mitragynine and ethanol
109 Toxic effects of fentanyl, alprazolam, and tramadol
110 diabetic ketoacidosis
111 Suicide due to toxic effects of cyclobenzaprine with diazepam
112 Bilateral pulmonary thromboemboli due to deep vein thrombosis associated with obesity
113
114
    ⋯ PhenoAge   epiTOC2     Zhang2019 StochClock1 StochClock2  StochClock3
1   ⋯ -22.791375  181.13486  30.09624  21.84555      4.513590   38.72373
2   ⋯ -17.402457   62.77680  25.51929  17.80645      7.576214   45.29077
3   ⋯ -20.579133  369.31879  33.18496  29.46791      1.795859   39.73101
4   ⋯ -20.439521  901.55171  30.34616  16.31163      2.873425   45.25659
5   ⋯ -30.526159  946.82365  40.70224  26.86126      3.694324   42.52529
6   ⋯ -21.974027  917.82742  41.69750  17.75092      9.953468   46.16633
7   ⋯ -20.421391  456.39942  24.81313  17.14162      8.469922   40.10796
8   ⋯ -22.062699  838.08977  37.18442  28.24137      8.600238   36.47719
9   ⋯  -9.884480 1429.80421  43.36969  36.17728     26.616832   43.90820
10  ⋯ -11.649303  302.05967  43.70871  34.56808     13.911975   43.20531
11  ⋯ -22.473605 1245.13714  29.48804  22.06732     15.799985   44.90300
12  ⋯ -35.508236  549.73552  10.20407  11.03315    -13.587002   38.89937
13  ⋯ -16.660257  228.43806  39.32562  24.79615     19.019247   43.01226
14  ⋯ -15.829706 1471.07436  31.16354  20.94538      3.842814   33.90269
15  ⋯  -5.440468 1359.81792  42.13414  27.89736     15.768064   49.59199
16  ⋯ -16.030792  126.77464  24.08520  18.51666      2.198469   43.09991
17  ⋯ -13.206898  300.12386  49.73528  34.17628     29.432692   45.30524
18  ⋯  -2.559894  266.56489  38.41806  23.72471     18.916332   46.42262
19  ⋯  -9.109668  556.14810  39.70604  22.03480     22.877660   49.00197
20  ⋯ -18.500426  587.93628  36.66341  16.98396      9.875848   45.34651
21  ⋯  -3.076856  367.45426  50.50771  37.17771     34.993178   45.80636
22  ⋯ -30.495376  144.04545  11.03668  18.12163    -15.548992   40.48513
23  ⋯ -11.679638   91.47075  38.03520  26.95430     16.768775   51.08503
24  ⋯ -20.958274  568.51908  30.81018  26.86435      1.485366   39.36469
25  ⋯  -7.207249 1008.95471  36.77153  21.05010     14.488600   46.98948
26  ⋯ -30.681731  744.08335  15.10747  10.45610     -8.391377   41.51215
27  ⋯ -12.987345   79.13760  37.89707  25.68568     13.467118   48.14104
28  ⋯ -22.434213 1272.32810  10.53949  13.62670    -11.456233   40.26024
29  ⋯ -11.506854  182.32383  32.51449  22.95587     11.130196   41.79165
30  ⋯ -11.845773  353.77275  39.31593  32.40067      9.790107   43.75431
⋮   ⋱ ⋮          ⋮           ⋮         ⋮           ⋮            ⋮
85  ⋯ -19.084346   74.749236 34.48763  29.51006      6.20649267 44.56846
86  ⋯ -25.279530 -112.057087 20.29733  23.60574    -11.16889228 38.57514
87  ⋯ -17.791800  -11.011478 44.81230  36.60548     13.24369510 43.16304
88  ⋯ -23.565363  128.749012 29.25634  26.58194     -0.02281981 44.91622
89  ⋯ -18.147567  102.784481 35.31320  29.88676      9.46521323 48.85387
90  ⋯ -16.793087   29.845747 41.68040  31.69441      7.83331729 44.53529
91  ⋯ -21.911102   14.049244 35.74688  35.28620      2.92136972 46.52256
92  ⋯  -8.547048  127.054806 42.59401  33.25454     11.80312795 44.14519
93  ⋯ -25.892587 -137.760859 19.15241  20.73654    -12.88104391 39.90960
94  ⋯ -32.507123   79.628406 17.93872  20.85331    -13.76198767 41.86440
95  ⋯ -12.054344  190.485481 44.10332  37.67107     15.79246440 45.31606
96  ⋯ -24.337030    2.221868 34.33469  25.20110      2.82810754 43.28189
97  ⋯  -8.308135  469.576519 42.31494  37.25331     11.53802780 40.60430
98  ⋯ -25.652079 -123.191876 20.31298  21.11819     -6.79026058 46.52831
99  ⋯ -10.739224   91.565446 44.82558  30.30496     17.59138955 47.19033
100 ⋯ -14.616435  -47.912604 25.23492  21.44423      5.56875064 46.70131
101 ⋯ -14.493979   41.540822 44.45844  32.32506     16.43892531 46.41015
102 ⋯ -19.752064  -98.908492 34.52192  29.55127      4.65732554 37.39332
103 ⋯ -23.197600  -67.869464 32.61099  23.77356     -0.27860942 44.37413
104 ⋯ -20.553331  177.438061 36.12474  27.65224     -1.80534719 44.78127
105 ⋯ -18.390741    1.288358 42.16441  35.42851     14.36824836 42.00159
106 ⋯  -9.858009   59.736717 42.14603  24.66672     26.59934249 47.60594
107 ⋯  -8.365389  -24.275479 45.17278  34.11843     11.96248491 48.31235
108 ⋯ -19.398138  109.750446 39.91151  27.05954     15.71993063 47.27033
109 ⋯ -33.398048 -119.098948 16.45387  15.66053    -14.85594932 38.89538
110 ⋯ -22.832184  -38.586821 31.98092  22.99109      1.30642419 45.81560
111 ⋯  -9.150546  -60.968314 45.08153  38.44926     19.87130289 46.61653
112 ⋯ -20.754439  -41.454759 33.98189  30.71411      1.35533133 42.77506
113 ⋯ -18.303709  -12.229472 45.82237  34.98453     15.49814493 42.14020
114 ⋯  -9.649889  173.512101 43.99944  37.29443     14.66776443 42.28124
    EAA_StochClock1 EAA_StochClock2 EAA_StochClock3 corticalClock
1    -3.1664033     -0.9963250       -5.1253923     40.40864
2    -2.7238284      9.4132725        2.2618458     38.11405
3     1.0946989     -9.2242857       -4.7332627     44.07033
4    -5.7125354      2.2614928        1.9542652     34.78782
5     0.3554117     -4.2645822       -1.5972339     46.06222
6   -10.2488188     -0.4544291        1.7704115     47.65431
7    -3.7621331      9.6947330       -2.9893153     36.07565
8     0.9885796     -0.5831638       -7.7820366     42.25234
9     4.8162826     10.6987049       -1.1028696     61.40346
10    5.4479178      1.6673345       -1.3956646     52.61040
11    0.4166200     15.8003000        1.6690273     32.41086
12   -4.6419756     -3.7907224       -3.2410022     13.16020
13   -4.3240078      6.7746058       -1.5887111     53.50167
14   -6.6808901     -5.9528354      -10.4248860     52.36108
15   -2.3432179      1.6866800        4.7859727     59.88429
16   -1.6401393      4.6477750        0.1393337     31.05004
17   -0.1725058      8.6165826       -0.2526318     62.25197
18   -2.7811330     10.9574259        2.3000966     49.34331
19   -7.0853581     10.6330192        4.4010021     53.32578
20  -11.3892498     -1.1442971        0.8822408     48.04638
21    2.4554561     13.5648200        0.1801366     68.13471
22    1.3260815     -7.5894553       -1.8602943     16.12162
23   -1.0454392      6.3608772        6.6891106     50.68663
24    0.7319773     -5.8612925       -4.6894803     45.09583
25   -4.3353326      8.3664376        3.0720103     48.76274
26   -8.5802853     -4.1053272       -1.2433790     23.04094
27   -6.0487899     -3.0632569        3.0616149     55.84980
28   -2.0484231     -1.6599528       -1.8801349     12.45951
29   -3.9234491      2.5590422       -2.3992278     45.71505
30    2.5335690     -3.6790292       -0.9833616     53.37296
⋮   ⋮               ⋮               ⋮               ⋮
85   5.61852349      2.53332097      0.9243813      40.35424
86   6.43672162     -3.82160373     -3.8386329      17.74969
87   5.99142868     -1.44993685     -1.7113290      56.43455
88   3.43734642     -2.47149593      1.4088438      37.13552
89   1.88701868     -0.94268418      4.4579446      46.74169
90   1.45383386     -6.24806686     -0.2707311      56.61238
91  10.64771668     -1.97629756      2.7417870      43.65253
92  -1.09423836     -9.01298191     -1.4126845      63.70642
93   3.94099187     -4.92150758     -2.4358253      20.89587
94   3.68428769     -6.41469913     -0.5493785      19.20445
95   2.94881370     -5.63589325     -0.3101630      64.87305
96  -0.18432283     -3.29405533     -0.6355851      46.00980
97   5.14536254     -5.60459531     -4.5434707      58.26908
98   3.57570122     -0.05521982      4.0461799      22.34490
99  -1.42951311      1.06101423      2.1109131      60.69883
100  2.40784408      9.85480023      3.9457866      28.66365
101 -0.15636177     -1.31594559      1.1940246      59.75837
102  6.03320834      1.59640163     -6.1824053      44.09990
103 -0.11797383     -3.95178112      0.7300561      37.15891
104  1.89333550     -8.53975785      0.7954439      48.57804
105  2.94709765     -3.38662254     -3.2145340      61.85347
106 -6.69427452     10.68121496      2.5948693      57.96225
107  3.13090269     -3.34339482      3.3696272      55.32088
108  0.55368923      7.76102439      3.1478032      48.44043
109 -0.01459438     -5.05966961     -3.2449935      11.36034
110  0.59345025      0.08224366      2.4449209      37.61231
111  5.59437008      1.50418420      1.3320608      68.10902
112  5.70215740     -4.15458374     -1.0740606      39.58549
113  1.75616324     -3.48122155     -3.2126220      62.62233
114  4.81301372     -3.08710648     -2.9348828      56.79421

In [34]:
# Save specific objects to an RData file
saveRDS(pheno_sub, file = "/vast/palmer/scratch/montalvo-ortiz/jjm262/00tclocks/00uthealth/00databases/05epigenome/00uthealth_brain-08032025.rds")

In [35]:
# Save Pheno and Beta in .CSV files
write.table(pheno_sub, file = "/vast/palmer/scratch/montalvo-ortiz/jjm262/00tclocks/00uthealth/00databases/05epigenome/00pheno_sub-08042025.txt",
          sep = '\t',
          quote = FALSE,
          row.names = FALSE)

In [7]:
# Round to three decimals
beta_rounded <- round(beta, 3)
# Save to CSV
write.csv(beta_rounded, file = "/vast/palmer/scratch/montalvo-ortiz/jjm262/00tclocks/00uthealth/00databases/05epigenome/01beta_rounded-08042025.csv", quote = FALSE, row.names = TRUE)