# Archive version, NOT EXECUTED

In [3]:
suppressPackageStartupMessages({
  library(ENmix)
  library(IlluminaHumanMethylationEPICmanifest)
  library(IlluminaHumanMethylationEPICanno.ilm10b2.hg19)
  library(parallel)
  library(methylCIPHER)
    library(glmnet);
    library(EpiDISH);
    library(dnaMethyAge)
})

In [72]:
# Reading phenotypic data
mf = "/gpfs/gibbs/pi/montalvo-ortiz/epigenomics/braindata/collaborations/consuelobassdata/brain_dataset/meta_BA9_brainbank_methylation_sub_3-29-22.csv"
mf = read.csv(mf)
mf$name <- paste0("BRA_", mf$Sentrix_ID)
head(mf$name)

[1] "BRA_201465920012_R01C01" "BRA_201465920012_R02C01"
[3] "BRA_201465920012_R03C01" "BRA_201465920012_R04C01"
[5] "BRA_201465920012_R05C01" "BRA_201465920012_R06C01"

In [12]:
# setting cores
num_threads <- detectCores() - 1
print(num_threads)
# set working directory
wkdir="/vast/palmer/scratch/montalvo-ortiz/jjm262/00tclocks/00uthealth/00databases/05epigenome"
setwd(wkdir)

[1] 47

In [14]:
path="/gpfs/gibbs/pi/montalvo-ortiz/epigenomics/braindata/collaborations/consuelobassdata/brain_dataset/idat_brain"
rgSet <- readidat(path = path,
                 recursive = TRUE,
                 force = TRUE)

[readidat] Found 123 files with suffix _Grn.idat

[readidat] Found 123 files with suffix _Red.idat

BRA_201465920012_R01C01 BRA_201465920012_R02C01 BRA_201465920012_R03C01
                1051943                 1051943                 1051943
BRA_201465920012_R04C01 BRA_201465920012_R05C01 BRA_201465920012_R06C01
                1051943                 1051943                 1051943
BRA_201465920012_R07C01 BRA_201465920012_R08C01 BRA_201465920048_R01C01
                1051943                 1051943                 1051943
BRA_201465920048_R02C01 BRA_201465920048_R03C01 BRA_201465920048_R04C01
                1051943                 1051943                 1051943
BRA_201465920048_R05C01 BRA_201465920048_R06C01 BRA_201465920048_R07C01
                1051943                 1051943                 1051943
BRA_201465920048_R08C01 BRA_201532190145_R01C01 BRA_201532190145_R02C01
                1051943                 1051815                 1051815
BRA_201532190145_R03C01 BRA_201532190145_R04C01 BRA_201532190145_R05C01
                1051815                 1051815                 1051815
BRA_201532190145_R06C01 BRA_201532190145_R07C01 BRA_201532190145_R08C01
                1051815                 1051815                 1051815
BRA_202273260185_R01C01 BRA_202273260185_R02C01 BRA_202273260185_R03C01
                1051815                 1051815                 1051815
BRA_202273260185_R04C01 BRA_202273260185_R05C01 BRA_202273260185_R06C01
                1051815                 1051815                 1051815
BRA_202273260185_R07C01 BRA_202273260185_R08C01 BRA_202273260186_R01C01
                1051815                 1051815                 1051815
BRA_202273260186_R02C01 BRA_202273260186_R03C01 BRA_202273260186_R04C01
                1051815                 1051815                 1051815
BRA_202273260186_R05C01 BRA_202273260186_R06C01 BRA_202273260186_R07C01
                1051815                 1051815                 1051815
BRA_202273260186_R08C01 BRA_202784980012_R01C01 BRA_202784980012_R02C01
                1051815                 1051815                 1051815
BRA_202787550031_R01C01 BRA_202787550031_R02C01 BRA_202787550031_R03C01
                1051815                 1051815                 1051815
BRA_202787550031_R04C01 BRA_202787550031_R05C01 BRA_202787550031_R06C01
                1051815                 1051815                 1051815
BRA_202787550031_R07C01 BRA_202787550031_R08C01 BRA_202787550059_R01C01
                1051815                 1051815                 1051815
BRA_202787550059_R02C01 BRA_202787550059_R03C01 BRA_202787550059_R04C01
                1051815                 1051815                 1051815
BRA_202787550059_R05C01 BRA_202787550059_R06C01 BRA_202787550059_R07C01
                1051815                 1051815                 1051815
BRA_202787550059_R08C01 BRA_202787550060_R01C01 BRA_202787550060_R02C01
                1051815                 1051815                 1051815
BRA_202787550060_R03C01 BRA_202787550060_R04C01 BRA_202787550060_R05C01
                1051815                 1051815                 1051815
BRA_202787550060_R06C01 BRA_202787550060_R07C01 BRA_202787550060_R08C01
                1051815                 1051815                 1051815
BRA_205016910016_R01C01 BRA_205016910016_R02C01 BRA_205016910016_R04C01
                1051943                 1051943                 1051943
BRA_205016910016_R05C01 BRA_205016910016_R06C01 BRA_205016910016_R07C01
                1051943                 1051943                 1051943
BRA_205016910016_R08C01 BRA_205016910070_R01C01 BRA_205016910070_R02C01
                1051943                 1051943                 1051943
BRA_205016910070_R03C01 BRA_205016910070_R04C01 BRA_205016910070_R05C01
                1051943                 1051943                 1051943
BRA_205016910070_R06C01 BRA_205016910070_R07C01 BRA_205016910070_R08C01
                1051943                 1051943                 1051943
BRA_205062740040_R01C01 BRA_205062740040_R02C01 BRA_205062740040_R03C01
                1051943                 1051943                 1051943
BRA_205062740040_R04C01 BRA_205062740040_R05C01 BRA_205062740040_R06C01
                1051943                 1051943                 1051943
BRA_205062740040_R07C01 BRA_205062740040_R08C01 BRA_205062740052_R01C01
                1051943                 1051943                 1051943
BRA_205062740052_R02C01 BRA_205062740052_R03C01 BRA_205062740052_R05C01
                1051943                 1051943                 1051943
BRA_205062740052_R06C01 BRA_205062740052_R07C01 BRA_205062740052_R08C01
                1051943                 1051943                 1051943
BRA_205062740070_R01C01 BRA_205062740070_R02C01 BRA_205062740070_R03C01
                1051943                 1051943                 1051943
BRA_205062740070_R04C01 BRA_205062740070_R05C01 BRA_205062740070_R06C01
                1051943                 1051943                 1051943
BRA_205062740070_R07C01 BRA_205062740070_R08C01 BRA_205062740140_R01C01
                1051943                 1051943                 1051943
BRA_205096370081_R01C01 BRA_205096370081_R02C01 BRA_205096370081_R03C01
                1051943                 1051943                 1051943
BRA_205096370081_R04C01 BRA_205096370081_R05C01 BRA_205096370081_R06C01
                1051943                 1051943                 1051943
BRA_205096370081_R07C01 BRA_205096370081_R08C01 BRA_205096370104_R01C01
                1051943                 1051943                 1051943
BRA_205096370104_R02C01 BRA_205096370104_R03C01 BRA_205096370104_R04C01
                1051943                 1051943                 1051943
BRA_205096370104_R05C01 BRA_205096370104_R06C01 BRA_205096370104_R07C01
                1051943                 1051943                 1051943
BRA_205096370104_R08C01 BRA_205134980005_R01C01 BRA_205134980005_R02C01
                1051943                 1051943                 1051943

Arrays with different sizes are forced to merge together


[readidat] Red Green Channel contains 1008711 probes and 123 Samples

In [35]:
# Perform QC
qc<-QCinfo(rgSet)
#QCinfo returns "detP","nbead","bisul","badsample","badCpG","outlier_sample"
#Samples with low quality data
qc$badsample
#CpGs with low quality data
qc$badCpG
#outlier samples
qc$outlier_sample

7  samples with percentage of low quality CpG value greater than  0.05  or bisulfite intensity less than  9777.351
44801  CpGs with percentage of low quality value greater than  0.05
Ploting qc_sample.jpg ...Done
Ploting qc_CpG.jpg ...Done
Identifying ourlier samples based on beta or total intensity values...
After excluding low quality samples and CpGs
0  samples are outliers based on averaged total intensity value
2  samples are outliers in beta value distribution
2  outlier samples were added into badsample list
Ploting freqpolygon_beta_beforeQC.jpg ...Done
Ploting freqpolygon_beta_afterQC.jpg ...Done

[1] "BRA_201465920012_R07C01" "BRA_201532190145_R07C01"
[3] "BRA_202787550059_R02C01" "BRA_202787550059_R08C01"
[5] "BRA_202787550060_R03C01" "BRA_202787550060_R06C01"
[7] "BRA_205096370104_R06C01" "BRA_205016910070_R08C01"
[9] "BRA_205096370104_R08C01"

    [1] "cg00007036"       "cg00008800"       "cg00013655"
    [4] "cg00028598"       "cg00033643"       "cg00039794"
    [7] "cg00055165"       "cg00058299"       "cg00084888"
   [10] "cg00090103"       "cg00090813"       "cg00099023"
   [13] "cg00160667"       "cg00161970"       "cg00162673"
   [16] "cg00164462"       "cg00179892"       "cg00199846"
   [19] "cg00207100"       "cg00212031"       "cg00213748"
   [22] "cg00214611"       "cg00223863"       "cg00225905"
   [25] "cg00275181"       "cg00285060"       "cg00313642"
   [28] "cg00332802"       "cg00334798"       "cg00343349"
   [31] "cg00356183"       "cg00399938"       "cg00401101"
   [34] "cg00416747"       "cg00418844"       "cg00428160"
   [37] "cg00433224"       "cg00448891"       "cg00455876"
   [40] "cg00465927"       "cg00472375"       "cg00501779"
   [43] "cg00503383"       "cg00531823"       "cg00536058"
   [46] "cg00611675"       "cg00632914"       "cg00637791"
   [49] "cg00659991"       "cg00678354"       "cg00680875"
   [52] "cg00729564"       "cg00742920"       "cg00748431"
   [55] "cg00771642"       "cg00781110"       "cg00795341"
   [58] "cg00798886"       "cg00803088"       "cg00808935"
   [61] "cg00817367"       "cg00843105"       "cg00857557"
   [64] "cg00859129"       "cg00864568"       "cg00870694"
   [67] "cg00877553"       "cg00878516"       "cg00898282"
   [70] "cg00917899"       "cg00922825"       "cg00974689"
   [73] "cg00988678"       "cg01002341"       "cg01006609"
   [76] "cg01019333"       "cg01036409"       "cg01040461"
   [79] "cg01061843"       "cg01068452"       "cg01070148"
   [82] "cg01094544"       "cg01096398"       "cg01097907"
   [85] "cg01111656"       "cg01145653"       "cg01153979"
   [88] "cg01166071"       "cg01166145"       "cg01168833"
   [91] "cg01177470"       "cg01188170"       "cg01191902"
   [94] "cg01217666"       "cg01224520"       "cg01230890"
   [97] "cg01238044"       "cg01239717"       "cg01241624"
  [100] "cg01266264"       "cg01270299"       "cg01295782"
  [103] "cg01306183"       "cg01351037"       "cg01370437"
  [106] "cg01392253"       "cg01395800"       "cg01399914"
  [109] "cg01403309"       "cg01413492"       "cg01414268"
  [112] "cg01445689"       "cg01446203"       "cg01471886"
  [115] "cg01483252"       "cg01483824"       "cg01485157"
  [118] "cg01504215"       "cg01541629"       "cg01547069"
  [121] "cg01554235"       "cg01556227"       "cg01588748"
  [124] "cg01590424"       "cg01593834"       "cg01594514"
  [127] "cg01614020"       "cg01615850"       "cg01653080"
  [130] "cg01659202"       "cg01659459"       "cg01663745"
  [133] "cg01666550"       "cg01678753"       "cg01680010"
  [136] "cg01683654"       "cg01703419"       "cg01731204"
  [139] "cg01742905"       "cg01748414"       "cg01755467"
  [142] "cg01778153"       "cg01788113"       "cg01789160"
  [145] "cg01793374"       "cg01807421"       "cg01816482"
  [148] "cg01826863"       "cg01835144"       "cg01842890"
  [151] "cg01845244"       "cg01850767"       "cg01856069"
  [154] "cg01866022"       "cg01874886"       "cg01878345"
  [157] "cg01891497"       "cg01923218"       "cg01934296"
  [160] "cg01938978"       "cg01941018"       "cg01957799"
  [163] "cg01967073"       "cg01994308"       "cg01995145"
  [166] "cg02000145"       "cg02005549"       "cg02011394"
  [169] "cg02012576"       "cg02020650"       "cg02049949"
  [172] "cg02050593"       "cg02069150"       "cg02084758"
  [175] "cg02090806"       "cg02125316"       "cg02129337"
  [178] "cg02153340"       "cg02155627"       "cg02157755"
  [181] "cg02183105"       "cg02190610"       "cg02202022"
  [184] "cg02227969"       "cg02230495"       "cg02234672"
  [187] "cg02243437"       "cg02260363"       "cg02260481"
  [190] "cg02262167"       "cg02266452"       "cg02266482"
  [193] "cg02269046"       "cg02273436"       "cg02292450"
  [196] "cg02295678"       "cg02302582"       "cg02305242"
  [199] "cg02308492"       "cg02314771"       "cg02315971"
  [202] "cg02346970"       "cg02354413"       "cg02361370"
  [205] "cg02363653"       "cg02370695"       "cg02376806"
  [208] "cg02390933"       "cg02394578"       "cg02441467"
  [211] "cg02447556"       "cg02470440"       "cg02478379"
  [214] "cg02482001"       "cg02487020"       "cg02491754"
  [217] "cg02495774"       "cg02514711"       "cg02514855"
  [220] "cg02518691"       "cg02570155"       "cg02578087"
  [223] "cg02589067"       "cg02599293"       "cg02605760"
  [226] "cg02613380"       "cg02637241"       "cg02638338"
  [229] "cg02639667"       "cg02645710"       "cg02651953"
  [232] "cg02658097"       "cg02666610"       "cg02692313"
  [235] "cg02711652"       "cg02711976"       "cg02736548"
  [238] "cg02742098"       "cg02746014"       "cg02746842"
  [241] "cg02758706"       "cg02760164"       "cg02764429"
  [244] "cg02769781"       "cg02788857"       "cg02792168"
  [247] "cg02804895"       "cg02810043"       "cg02831300"
  [250] "cg02839557"       "cg02851212"       "cg02861733"
  [253] "cg02863594"       "cg02890368"       "cg02919564"
  [256] "cg02925367"       "cg02927870"       "cg02930763"
  [259] "cg02933100"       "cg02949469"       "cg02954252"
  [262] "cg02978184"       "cg02988422"       "cg02999463"
  [265] "cg03007623"       "cg03023189"       "cg03036167"
  [268] "cg03047785"       "cg03052502"       "cg03055449"
  [271] "cg03066754"       "cg03078689"       "cg03088475"
  [274] "cg03090171"       "cg03092607"       "cg03100068"
  [277] "cg03119028"       "cg03124478"       "cg03151810"
  [280] "cg03155755"       "cg03161803"       "cg03172996"
  [283] "cg03174931"       "cg03179450"       "cg03186367"
  [286] "cg03205007"       "cg03219968"       "cg03226218"
  [289] "cg03255942"       "cg03259207"       "cg03259925"
  [292] "cg03299611"       "cg03310242"       "cg03315935"
  [295] "cg03338348"       "cg03338968"       "cg03357803"
  [298] "cg03429255"       "cg03450794"       "cg03460049"
  [301] "cg03464336"       "cg03464406"       "cg03465511"
  [304] "cg03471999"       "cg03475293"       "cg03486157"
  [307] "cg03488097"       "cg03494266"       "cg03520265"
  [310] "cg03522743"       "cg03532045"       "cg03538607"
  [313] "cg03547446"       "cg03551051"       "cg03558399"
  [316] "cg03562350"       "cg03567028"       "cg03568042"
  [319] "cg03576123"       "cg03579738"       "cg03586128"
  [322] "cg03603114"       "cg03611007"       "cg03631223"
  [325] "cg03647452"       "cg03666441"       "cg03667862"
  [328] "cg03679005"       "cg03687305"       "cg03705894"
  [331] "cg03750315"       "cg03767353"       "cg03807873"
  [334] "cg03811055"       "cg03839554"       "cg03852219"
  [337] "cg03859313"       "cg03869498"       "cg03887218"
  [340] "cg03891652"       "cg03896944"       "cg03904534"
  [343] "cg03913456"       "cg03923227"       "cg03928429"
  [346] "cg03929570"       "cg03950268"       "cg03972665"
  [349] "cg03983645"       "cg03996861"       "cg04004297"
  [352] "cg04013089"       "cg04016144"       "cg04024481"
  [355] "cg04058281"       "cg04066396"       "cg04085771"
  [358] "cg04088773"       "cg04097963"       "cg04101442"
  [361] "cg04105547"       "cg04105726"       "cg04111078"
  [364] "cg04163474"       "cg04201563"       "cg04208499"
  [367] "cg04221794"       "cg04229253"       "cg04236079"
  [370] "cg04252889"       "cg04299170"       "cg04311686"
  [373] "cg04327181"       "cg04338281"       "cg04339882"
  [376] "cg04355444"       "cg04360491"       "cg04365817"
  [379] "cg04368789"       "cg04369291"       "cg04385144"
  [382] "cg04392293"       "cg04395230"       "cg04413673"
  [385] "cg04442576"       "cg04448376"       "cg04472373"
  [388] "cg04481077"       "cg04500577"       "cg04513882"
  [391] "cg04538307"       "cg04599342"       "cg04605287"
  [394] "cg04608651"       "cg04609126"       "cg04614655"
  [397] "cg04624228"       "cg04628434"       "cg04632255"
  [400] "cg04654530"       "cg04682916"       "cg04688351"
  [403] "cg04704193"       "cg04706183"       "cg04741880"
  [406] "cg04742780"       "cg04779361"       "cg04829364"
  [409] "cg04834608"       "cg04838627"       "cg04844534"
  [412] "cg04845847"       "cg04854908"       "cg04863452"
  [415] "cg04868078"       "cg04883139"       "cg04883903"
  [418] "cg04895321"       "cg04900823"       "cg04911366"
  [421] "cg04918900"       "cg04925085"       "cg04940824"
  [424] "cg04947385"       "cg04959674"       "cg04960987"
  [427] "cg04963066"       "cg04965141"       "cg05006903"
  [430] "cg05009394"       "cg05021846"       "cg05064121"
  [433] "cg05075692"       "cg05104476"       "cg05112824"
  [436] "cg05147983"       "cg05154019"       "cg05166248"
  [439] "cg05209770"       "cg05230316"       "cg05230942"
  [442] "cg05241839"       "cg05244234"       "cg05252626"
  [445] "cg05255305"       "cg05262724"       "cg05269017"
  [448] "cg05270922"       "cg05278650"       "cg05288475"
  [451] "cg05304806"       "cg05312353"       "cg05339066"
  [454] "cg05344293"       "cg05349980"       "cg05358715"
  [457] "cg05360422"       "cg05362548"       "cg05364759"
  [460] "cg05366139"       "cg05372444"       "cg05382797"
  [463] "cg05403431"       "cg05408877"       "cg05429674"
  [466] "cg05433490"       "cg05435398"       "cg05454400"
  [469] "cg05460318"       "cg05509352"       "cg05518022"
  [472] "cg05532204"       "cg05533783"       "cg05534333"
  [475] "cg05538151"       "cg05544622"       "cg05593653"
  [478] "cg05611648"       "cg05613094"       "cg05616550"
  [481] "cg05619116"       "cg05621349"       "cg05624862"
  [484] "cg05638929"       "cg05642873"       "cg05658717"
  [487] "cg05701341"       "cg05711036"       "cg05719164"
  [490] "cg05735180"       "cg05770971"       "cg05781826"
  [493] "cg05784856"       "cg05808399"       "cg05816844"
  [496] "cg05842348"       "cg05856102"       "cg05865243"
  [499] "cg05871472"       "cg05874523"       "cg05894122"
  [502] "cg05896563"       "cg05915794"       "cg05920635"
  [505] "cg05935660"       "cg05955334"       "cg05960997"
  [508] "cg05962325"       "cg05971678"       "cg05997131"
  [511] "cg06006401"       "cg06011925"       "cg06018447"
  [514] "cg06019884"       "cg06027927"       "cg06053110"
  [517] "cg06091086"       "cg06092146"       "cg06094323"
  [520] "cg06109664"       "cg06137672"       "cg06140670"
  [523] "cg06146607"       "cg06160295"       "cg06161952"
  [526] "cg06166515"       "cg06194003"       "cg06194479"
  [529] "cg06211794"       "cg06241792"       "cg06243866"
  [532] "cg06286642"       "cg06293983"       "cg06295987"
  [535] "cg06302718"       "cg06322277"       "cg06333492"
  [538] "cg06340447"       "cg06350542"       "cg06352041"
  [541] "cg06354075"       "cg06354455"       "cg06357549"
  [544] "cg06366585"       "cg06368590"       "cg06379361"
  [547] "cg06379565"       "cg06440553"       "cg06500074"
  [550] "cg06503255"       "cg06505107"       "cg06528214"
  [553] "cg06534952"       "cg06538336"       "cg06549530"
  [556] "cg06568056"       "cg06581840"       "cg06587249"
  [559] "cg06588676"       "cg06593906"       "cg06620353"
  [562] "cg06620390"       "cg06651605"       "cg06679760"
  [565] "cg06682282"       "cg06695338"       "cg06713767"
  [568] "cg06732825"       "cg06759058"       "cg06774039"
  [571] "cg06822699"       "cg06833732"       "cg06850186"
  [574] "cg06879219"       "cg06881803"       "cg06895834"
  [577] "cg06921011"       "cg06923084"       "cg06956613"
  [580] "cg06963219"       "cg07007834"       "cg07023803"
  [583] "cg07028821"       "cg07028914"       "cg07035811"
  [586] "cg07040133"       "cg07056260"       "cg07065220"
  [589] "cg07066474"       "cg07068956"       "cg07070466"
  [592] "cg07077665"       "cg07077900"       "cg07082715"
  [595] "cg07083902"       "cg07104919"       "cg07108512"
  [598] "cg07113870"       "cg07124322"       "cg07127945"
  [601] "cg07140217"       "cg07162861"       "cg07178143"
  [604] "cg07179078"       "cg07207136"       "cg07215822"
  [607] "cg07227350"       "cg07235608"       "cg07251576"
  [610] "cg07258408"       "cg07262012"       "cg07277190"
  [613] "cg07356114"       "cg07360021"       "cg07377876"
  [616] "cg07387607"       "cg07391218"       "cg07393816"
  [619] "cg07443778"       "cg07450135"       "cg07474652"
  [622] "cg07479492"       "cg07497933"       "cg07538239"
  [625] "cg07541085"       "cg07543572"       "cg07582470"
  [628] "cg07588778"       "cg07603056"       "cg07615875"
  [631] "cg07621312"       "cg07638282"       "cg07650623"
  [634] "cg07660862"       "cg07667458"       "cg07667765"
  [637] "cg07678032"       "cg07694390"       "cg07702255"
  [640] "cg07703679"       "cg07706471"       "cg07723510"
  [643] "cg07723559"       "cg07744547"       "cg07749655"
  [646] "cg07751222"       "cg07752472"       "cg07810469"
  [649] "cg07856962"       "cg07870252"       "cg07876051"
  [652] "cg07882021"       "cg07882546"       "cg07889003"
  [655] "cg07902192"       "cg07904290"       "cg07912251"
  [658] "cg07918723"       "cg07939587"       "cg07940218"
  [661] "cg07944399"       "cg07946923"       "cg07963363"
  [664] "cg08015590"       "cg08020762"       "cg08038667"
  [667] "cg08050536"       "cg08072101"       "cg08081346"
  [670] "cg08082791"       "cg08084154"       "cg08137080"
  [673] "cg08143046"       "cg08149193"       "cg08163785"
  [676] "cg08174789"       "cg08186508"       "cg08201854"
  [679] "cg08204043"       "cg08231348"       "cg08242338"
  [682] "cg08252887"       "cg08254639"       "cg08265308"
  [685] "cg08266223"       "cg08293097"       "cg08294136"
  [688] "cg08330327"       "cg08360820"       "cg08361130"
  [691] "cg08385249"       "cg08387896"       "cg08422863"
  [694] "cg08430409"       "cg08431447"       "cg08434295"
  [697] "cg08445263"       "cg08450058"       "cg08451977"
  [700] "cg08452456"       "cg08457421"       "cg08463298"
  [703] "cg08468599"       "cg08481873"       "cg08492202"
  [706] "cg08497487"       "cg08515845"       "cg08535260"
  [709] "cg08536805"       "cg08537890"       "cg08548396"
  [712] "cg08556636"       "cg08602173"       "cg08605840"
  [715] "cg08624472"       "cg08630869"       "cg08648727"
  [718] "cg08662043"       "cg08687137"       "cg08689926"
  [721] "cg08701937"       "cg08703522"       "cg08718490"
  [724] "cg08724409"       "cg08742041"       "cg08742408"
  [727] "cg08760073"       "cg08795589"       "cg08798692"
  [730] "cg08821715"       "cg08851851"       "cg08872363"
  [733] "cg08875198"       "cg08881780"       "cg08911536"
  [736] "cg08913815"       "cg08920807"       "cg08926642"
  [739] "cg08928871"       "cg08942073"       "cg08947187"
  [742] "cg08953666"       "cg08961558"       "cg08962243"
  [745] "cg08973565"       "cg08993197"       "cg09029959"
  [748] "cg09045935"       "cg09049376"       "cg09052544"
  [751] "cg09054644"       "cg09071690"       "cg09072865"
  [754] "cg09073539"       "cg09102880"       "cg09114151"
  [757] "cg09120138"       "cg09121569"       "cg09127400"
  [760] "cg09143576"       "cg09154837"       "cg09168548"
  [763] "cg09180070"       "cg09202227"       "cg09203469"
  [766] "cg09210336"       "cg09216375"       "cg09228194"
  [769] "cg09240001"       "cg09250458"       "cg09282336"
  [772] "cg09285672"       "cg09293387"       "cg09297514"
  [775] "cg09301410"       "cg09304136"       "cg09317036"
  [778] "cg09321400"       "cg09344943"       "cg09350919"
  [781] "cg09360770"       "cg09371829"       "cg09372546"
  [784] "cg09428537"       "cg09431544"       "cg09460641"
  [787] "cg09462281"       "cg09478603"       "cg09490880"
  [790] "cg09507643"       "cg09540612"       "cg09543819"
  [793] "cg09554951"       "cg09575189"       "cg09584492"
  [796] "cg09607566"       "cg09610253"       "cg09622432"
  [799] "cg09638793"       "cg09640718"       "cg09642777"
  [802] "cg09646795"       "cg09650414"       "cg09656942"
  [805] "cg09669178"       "cg09672912"       "cg09680719"
  [808] "cg09706833"       "cg09727992"       "cg09734952"
  [811] "cg09753193"       "cg09754111"       "cg09783858"
  [814] "cg09783905"       "cg09816855"       "cg09833720"
  [817] "cg09835225"       "cg09835486"       "cg09852199"
  [820] "cg09865425"       "cg09897970"       "cg09911092"
  [823] "cg09920051"       "cg09926867"       "cg09929831"
  [826] "cg09932747"       "cg09954723"       "cg09964854"
  [829] "cg10009224"       "cg10021924"       "cg10022553"
  [832] "cg10040162"       "cg10044466"       "cg10066740"
  [835] "cg10068917"       "cg10079867"       "cg10091523"
  [838] "cg10102721"       "cg10107958"       "cg10109500"
  [841] "cg10111314"       "cg10137463"       "cg10144719"
  [844] "cg10156544"       "cg10157839"       "cg10168149"
  [847] "cg10169177"       "cg10177207"       "cg10213302"
  [850] "cg10221930"       "cg10267609"       "cg10297430"
  [853] "cg10322360"       "cg10336131"       "cg10342614"
  [856] "cg10350607"       "cg10353785"       "cg10363397"
  [859] "cg10371977"       "cg10387963"       "cg10427793"
  [862] "cg10427864"       "cg10439914"       "cg10442932"
  [865] "cg10449276"       "cg10490271"       "cg10501278"
  [868] "cg10502904"       "cg10503326"       "cg10512498"
  [871] "cg10523380"       "cg10537847"       "cg10540928"
  [874] "cg10588470"       "cg10589577"       "cg10599345"
  [877] "cg10604731"       "cg10623802"       "cg10625758"
  [880] "cg10638118"       "cg10664338"       "cg10668399"
  [883] "cg10669285"       "cg10690152"       "cg10698404"
  [886] "cg10698984"       "cg10699852"       "cg10709494"
  [889] "cg10713320"       "cg10722938"       "cg10739132"
  [892] "cg10747483"       "cg10750989"       "cg10753423"
  [895] "cg10763234"       "cg10773670"       "cg10776591"
  [898] "cg10782380"       "cg10793234"       "cg10795666"
  [901] "cg10799646"       "cg10838270"       "cg10841270"
  [904] "cg10858327"       "cg10875454"       "cg10888299"
  [907] "cg10891259"       "cg10904972"       "cg10905736"
  [910] "cg10907232"       "cg10907727"       "cg10927719"
  [913] "cg10951305"       "cg10986455"       "cg10989862"
  [916] "cg10994639"       "cg11003573"       "cg11050862"
  [919] "cg11067468"       "cg11081482"       "cg11105216"
  [922] "cg11113644"       "cg11119419"       "cg11131351"
  [925] "cg11138035"       "cg11143796"       "cg11155992"
  [928] "cg11156873"       "cg11160054"       "cg11166741"
  [931] "cg11170680"       "cg11172857"       "cg11178574"
  [934] "cg11203670"       "cg11226901"       "cg11231864"
  [937] "cg11237951"       "cg11243371"       "cg11250301"
  [940] "cg11256764"       "cg11270042"       "cg11271157"
  [943] "cg11271681"       "cg11274464"       "cg11288801"
  [946] "cg11320369"       "cg11323985"       "cg11342694"
  [949] "cg11344566"       "cg11345323"       "cg11347328"
  [952] "cg11347531"       "cg11360098"       "cg11371879"
  [955] "cg11384718"       "cg11395453"       "cg11405538"
  [958] "cg11408224"       "cg11410726"       "cg11415653"
  [961] "cg11438011"       "cg11439308"       "cg11464377"
  [964] "cg11466962"       "cg11468348"       "cg11474250"
  [967] "cg11478607"       "cg11523661"       "cg11524184"
  [970] "cg11528029"       "cg11538573"       "cg11539882"
  [973] "cg11542402"       "cg11551289"       "cg11553116"
  [976] "cg11558328"       "cg11561443"       "cg11564339"
  [979] "cg11569008"       "cg11573679"       "cg11582634"
  [982] "cg11595411"       "cg11626785"       "cg11630696"
  [985] "cg11654179"       "cg11654904"       "cg11660308"
  [988] "cg11661868"       "cg11665745"       "cg11667683"
  [991] "cg11669516"       "cg11672338"       "cg11674627"
  [994] "cg11694418"       "cg11697464"       "cg11706467"
  [997] "cg11715725"       "cg11720358"       "cg11731745"
 [1000] "cg11737232"       "cg11761572"       "cg11766011"
 [1003] "cg11767392"       "cg11779900"       "cg11783625"
 [1006] "cg11789421"       "cg11797994"       "cg11821269"
 [1009] "cg11822088"       "cg11843188"       "cg11849422"
 [1012] "cg11849573"       "cg11850622"       "cg11851456"

[1] "BRA_205016910070_R08C01" "BRA_205096370104_R08C01"

In [37]:
# First estimate Betas
meta = getmeth(rgSet)
beta = getB(meta)

# filter low quality and outlier values, remove rows and
# columns with too many (rthre=0.05,cthre=0.05, 5% in default) missing values,
# and then do imputation
#b3=qcfilter(beta, qcscore=qc, rmcr=TRUE, rthre=0.05,
#              cthre=0.05, impute=TRUE)

In [38]:
# Perform SVA analysis
sva <- ctrlsva(rgSet)
sva = as.data.frame(sva)
sva$name = rownames(sva)

8  surrogate variables explain  95.37677 % of
    data variation

In [18]:
celltype = estimateCellProp(userdata=rgSet,
         refdata="FlowSorted.DLPFC.450k",
         nonnegative = TRUE, normalize=TRUE)

Loading required package: IlluminaHumanMethylation450kmanifest

In [73]:
# Merge celltypes
celltype$name = celltype$Sample_Name
pheno = merge(mf, celltype, by = c('name'))
pheno = merge(pheno, sva, by = c('name'))

In [44]:
# Estimate clocks using methylCIPHER
# Need to transpose the matrix, samples in columns and cpg in rows
beta = as.data.frame(t(beta))
calcCoreClocks(beta, pheno)

Please remember to cite the core Clocks you have used! Please refer to the README.md file for assistance.

    name                    SAB   Sentrix_ID          Year Ethnicity Gender Age
1   BRA_201465920012_R01C01 67917 201465920012_R01C01 2018 Hispanic  Male   44
2   BRA_201465920012_R02C01 67927 201465920012_R02C01 2018 Black     Female 32
3   BRA_201465920012_R03C01 67928 201465920012_R03C01 2018 Black     Male   53
4   BRA_201465920012_R04C01 67929 201465920012_R04C01 2018 White     Female 36
5   BRA_201465920012_R05C01 67930 201465920012_R05C01 2018 White     Male   48
6   BRA_201465920012_R06C01 67931 201465920012_R06C01 2018 White     Male   52
7   BRA_201465920012_R07C01 67941 201465920012_R07C01 2018 White     Male   64
8   BRA_201465920012_R08C01 67943 201465920012_R08C01 2018 White     Male   33
9   BRA_201465920048_R01C01 67944 201465920048_R01C01 2018 White     Female 50
10  BRA_201465920048_R02C01 67945 201465920048_R02C01 2018 Black     Male   61
11  BRA_201465920048_R03C01 67933 201465920048_R03C01 2018 White     Female 55
12  BRA_201465920048_R04C01 67935 201465920048_R04C01 2018 White     Male   35
13  BRA_201465920048_R05C01 67938 201465920048_R05C01 2018 Black     Male   19
14  BRA_201465920048_R06C01 67940 201465920048_R06C01 2018 White     Male   55
15  BRA_201465920048_R07C01 67946 201465920048_R07C01 2018 White     Male   51
16  BRA_201465920048_R08C01 67948 201465920048_R08C01 2018 Hispanic  Male   58
17  BRA_201532190145_R01C01 67974 201532190145_R01C01 2018 White     Female 31
18  BRA_201532190145_R02C01 67976 201532190145_R02C01 2018 White     Female 69
19  BRA_201532190145_R03C01 67977 201532190145_R03C01 2018 White     Female 48
20  BRA_201532190145_R04C01 67978 201532190145_R04C01 2018 White     Female 55
21  BRA_201532190145_R05C01 67979 201532190145_R05C01 2018 White     Female 53
22  BRA_201532190145_R06C01 67980 201532190145_R06C01 2018 White     Female 70
23  BRA_201532190145_R07C01 67909 201532190145_R07C01 2018 Black     Male   56
24  BRA_201532190145_R08C01 67915 201532190145_R08C01 2018 White     Male   22
25  BRA_202273260185_R01C01 67926 202273260185_R01C01 2018 Hispanic  Male   52
26  BRA_202273260185_R02C01 67937 202273260185_R02C01 2018 White     Male   47
27  BRA_202273260185_R03C01 67968 202273260185_R03C01 2018 Black     Female 45
28  BRA_202273260185_R04C01 67969 202273260185_R04C01 2018 Black     Male   28
29  BRA_202273260185_R05C01 67970 202273260185_R05C01 2018 White     Male   62
30  BRA_202273260185_R06C01 67971 202273260185_R06C01 2018 Black     Male   19
⋮   ⋮                       ⋮     ⋮                   ⋮    ⋮         ⋮      ⋮
94  BRA_205062740052_R06C01 67994 205062740052_R06C01 2022 Hispanic  Male   59
95  BRA_205062740052_R07C01 67982 205062740052_R07C01 2022 White     Male   39
96  BRA_205062740052_R08C01 67990 205062740052_R08C01 2022 White     Male   52
97  BRA_205062740070_R01C01 79220 205062740070_R01C01 2022 White     Male   58
98  BRA_205062740070_R02C01 67985 205062740070_R02C01 2022 White     Male   43
99  BRA_205062740070_R03C01 79225 205062740070_R03C01 2022 Black     Female 69
100 BRA_205062740070_R04C01 79218 205062740070_R04C01 2022 Black     Male   22
101 BRA_205062740070_R05C01 79200 205062740070_R05C01 2022 White     Male   23
102 BRA_205062740070_R06C01 79213 205062740070_R06C01 2022 Black     Male   70
103 BRA_205062740070_R07C01 79209 205062740070_R07C01 2022 White     Male   45
104 BRA_205062740070_R08C01 79205 205062740070_R08C01 2022 White     Male   63
105 BRA_205062740140_R01C01 67983 205062740140_R01C01 2022 White     Female 24
106 BRA_205096370081_R01C01 79214 205096370081_R01C01 2022 White     Male   62
107 BRA_205096370081_R02C01 79229 205096370081_R02C01 2022 Black     Male   28
108 BRA_205096370081_R03C01 67999 205096370081_R03C01 2022 White     Male   64
109 BRA_205096370081_R04C01 79228 205096370081_R04C01 2022 White     Male   40
110 BRA_205096370081_R05C01 79226 205096370081_R05C01 2022 Black     Female 41
111 BRA_205096370081_R06C01 79230 205096370081_R06C01 2022 Black     Female 46
112 BRA_205096370081_R07C01 67992 205096370081_R07C01 2022 Black     Female 64
113 BRA_205096370081_R08C01 67997 205096370081_R08C01 2022 Hispanic  Male   61
114 BRA_205096370104_R01C01 79221 205096370104_R01C01 2022 Black     Female 60
115 BRA_205096370104_R02C01 79216 205096370104_R02C01 2022 White     Male   48
116 BRA_205096370104_R03C01 79217 205096370104_R03C01 2022 Hispanic  Male   19
117 BRA_205096370104_R04C01 67984 205096370104_R04C01 2022 White     Male   37
118 BRA_205096370104_R05C01 79212 205096370104_R05C01 2022 Black     Female 65
119 BRA_205096370104_R06C01 79201 205096370104_R06C01 2022 Hispanic  Male   42
120 BRA_205096370104_R07C01 79215 205096370104_R07C01 2022 Hispanic  Male   44
121 BRA_205096370104_R08C01 67998 205096370104_R08C01 2022 White     Male   28
122 BRA_205134980005_R01C01 79238 205134980005_R01C01 2022 Black     Female 66
123 BRA_205134980005_R02C01 79239 205134980005_R02C01 2022 Black     Male   64
    PMIhrs pH
1   32.67  5.91
2   31.57  6.56
3   28.65  6.79
4   28.20  6.80
5   31.30  6.44
6   31.92  6.38
7   26.35  6.40
8   10.57  6.72
9    9.55  6.63
10  37.40  6.64
11  28.78  7.02
12  18.20  6.20
13  36.03  6.63
14  23.75  5.84
15  22.98  6.73
16  26.48  6.82
17  23.60  6.56
18  24.82  6.42
19  31.97  6.73
20  27.62  6.40
21  30.15  6.89
22  28.60  6.57
23  30.25  6.48
24  53.82  6.63
25  47.92  6.49
26  27.62  6.23
27  13.07  6.49
28  23.97  6.68
29  23.82  7.29
30  21.60  7.05
⋮   ⋮      ⋮
94  32.35  6.80
95  16.52  6.53
96  23.43  6.77
97  15.05    NA
98  25.17  6.44
99  20.32    NA
100 22.10    NA
101 16.78  6.52
102 27.32    NA
103 20.63    NA
104 14.55    NA
105 14.50  6.50
106 24.28    NA
107 39.83    NA
108 43.33  6.53
109 33.48    NA
110 38.70    NA
111 12.32    NA
112 28.03  6.62
113 26.38  6.89
114 23.80    NA
115 13.17    NA
116 28.88    NA
117 11.73  6.04
118 19.25    NA
119 33.45    NA
120 56.92    NA
121 32.33  7.02
122 23.83    NA
123 44.73    NA
    Cause_of_Death
1   acute carisoprodol toxicity
2   undetermined
3   acute toxicity of cocaine and ethanol
4   toxic effects of methadone
5   GSW
6   cardiovascular disease, not opioid
7   ruptured AAA
8   multi overdose: benzodiazepine, amphetamine, cocaine, EtOH, and opioid
9   sepsis
10  Cardiovascular disease
11  carciovascular disease
12  combined toxicity of heroin, methamphetamine, alprazolam and ethanol
13  combined toxic effects of alprazolam, codeine and morphine
14  Cardiovascular disease
15  cocaine and opioid OD
16  Cardiovascular disease
17  opioid, amitriptyline, diphenhydramine, hydroxyzine, promethazine, and benzo OD
18  Cardiovascular disease
19  prescription medication OD
20  opioid, EtOH, benzodiazepine, diphenhydramine and gabapentin OD
21  alcohol and diphenhydramine OD
22  fall
23  Pulmonary Embolism
24  Toxic effects of U-47700
25  Cardiovascular disease
26  Cardiovascular disease
27  toxic effect of cocaine
28  cirrhosis and ESRD
29  Cardiovascular disease with signs of chronic alcoholism (hepatic fibrosis)
30  GSW
⋮   ⋮
94  Cardiovascular disease
95  Cardiovascular disease
96  Cardiovascular disease
97  Acute and chronic ethanolism with toxic effects of chlordiazepoxide
98  toxic effects of methamphetamine
99  Atherosclerotic and hypertensive cardiovascular disease
100 Combined alprazolam, etizolam, and fentanyl toxicities
101 mitragynine, benzodiazepine, and loperamide OD
102 Pulmonary thromboembolism due to deep vein thromboses of lower extremities
103 Acute toxicity due to the combined effects of fentanyl, midazolam, diphenhydramine, amphetamine, and bupropion
104 Suicide due to combined acetaminophen, hydrocodone, zolpidem toxicity
105 opioid, benzodiazepine and SSRI OD
106 Acute Methamphetamine Toxicity
107 Complications of morbid obesity and asthma
108 Cardiovascular disease
109 Combined toxic effects of fentanyl, alprazolam, methamphetamine, and MDMA
110 hypertensive and atherosclerotic cardiovascular disease
111 Toxic effects of fentanyl, codeine, hydrocodone, quetiapine, and diphenhydramine
112 Cardiovascular disease
113 Cardiovascular disease
114 Acute cocaine toxicity
115 Combined toxic effects of heroin, methamphetmine, mitragynine and ethanol
116 Toxic effects of fentanyl, alprazolam, and tramadol
117 diabetic ketoacidosis
118 Suicide due to toxic effects of cyclobenzaprine with diazepam
119 GSW
120 Bilateral pulmonary thromboemboli due to deep vein thrombosis associated with obesity
121 cocaine, opioid, and benzodiazepine OD
122
123
    ⋯ PC3         PC4          PC5         PC6          PC7         PC8
1   ⋯  -6665.8843   1293.0304  -5005.23120  2870.01084  -3640.1573     355.5046
2   ⋯  -4262.4880  -3302.8470  -1485.83904 -6463.84352  -1715.2361    2302.3781
3   ⋯   -988.6257  -8945.0667  -5556.49206  1126.86676  -4362.8206    1257.2628
4   ⋯  -2545.9918 -13250.4964  -2082.82146 -4780.32599  -5395.5371   -1540.2280
5   ⋯  -2974.7844 -10869.5795  -5945.75523 -1059.95173  -6963.1584    2966.0035
6   ⋯  -2278.0445 -14641.3552  -4522.12854    -3.86258  -3440.9959    1329.0686
7   ⋯  -2967.0714 -10692.0569   1858.70118  1448.24412  -2024.6519   -2061.6679
8   ⋯  -5088.2332  11016.2750  -4462.38435  1794.73226   -820.1338   -1034.7168
9   ⋯  -3284.8649    187.7708  -1597.55280 -3680.88142  -1699.2859     590.2310
10  ⋯  -2548.4546  -3748.7566  -2633.85702   104.38850   -651.0705     785.4020
11  ⋯   2943.6878  -3825.0811  -2748.52840 -5500.57009  -1450.3660    2324.3621
12  ⋯   9462.6391 -10604.1888  -1727.96346   664.14644  -3581.3157     748.0825
13  ⋯   2845.8218  -9316.4867  -6634.48625  -126.30027  -3778.0404    2460.2815
14  ⋯   7778.7644  -7197.7040  -6768.00352  1090.65423  -4380.7075    3853.5769
15  ⋯   5341.9128 -12173.2244   -368.00075  -158.13531  -4448.5568   -2980.1615
16  ⋯   3424.2699   -112.6223   -651.91646  -197.09408  -3487.1416   -4920.1739
17  ⋯  -9732.0354   5319.3273  -1541.96995 -7021.36954  -4268.7950     242.5200
18  ⋯  -7242.3635   2236.6636   1062.44685 -7196.46637  -2310.5949   -1260.0535
19  ⋯  -7501.6211   4340.0783    227.01424 -9042.59180  -1863.8628     -17.4089
20  ⋯  -3965.1545    680.9233  -1924.34607 -6663.13564  -3845.6939    2143.3157
21  ⋯  -2823.3871  -5448.7089    775.57175 -6169.68920  -6128.8901    2418.3444
22  ⋯   -203.3576  -5025.5817   -773.01517 -8771.18635  -4224.2191    1047.9742
23  ⋯   4412.7124  -4259.8571  11672.09558  -533.80167  -2558.0157  -14390.6189
24  ⋯  -2728.4669  17489.2934  -3315.39766  1921.07597  -4264.9230    -988.8265
25  ⋯ -14538.0593   1579.6925  -1948.08147  3231.91539    805.3035   -2206.1611
26  ⋯  -4837.6576  -2113.8179  -3389.66329  1019.22236  -3518.0092     -80.0354
27  ⋯   2904.4205  -8097.9896   5030.79793 -3572.62139   2330.7556    1098.7878
28  ⋯   5948.1803  -3755.5483    -94.92674  1311.77378    361.8461     705.0002
29  ⋯   3070.7260   4191.8866    489.29650  2828.85051   1542.7420   -2450.5514
30  ⋯   5887.5013  -3507.4133   2430.38115  1468.61301   3103.0225     321.1489
⋮   ⋱ ⋮           ⋮            ⋮           ⋮            ⋮           ⋮
94  ⋯  -5668.7682  -6158.46861  2144.5417    4639.09444  1805.01144 -2425.4879
95  ⋯  -1058.9105    -88.27759  -705.7584    2078.43860  1363.82925 -1793.1447
96  ⋯  15051.1881  18888.86247 -6009.4811      78.25589 -2903.82228 -4242.8403
97  ⋯  -8432.7815   5855.76352  2307.8286    4353.64030  3091.82810  -868.9399
98  ⋯  -7206.3010   -735.96033   393.8604    3107.90511  2442.38774 -2070.9743
99  ⋯   2055.7296   7155.79278  5615.2500   -8039.84903   107.18582 -2076.1262
100 ⋯    675.3174  -2926.28773   635.8986    3081.04209  2633.13414 -2487.1951
101 ⋯   3488.8259    467.84112   725.9511    2202.59977   701.35797  1303.0236
102 ⋯   5098.5518   -946.70435  1494.0529    2324.93068  2338.79685  -509.2862
103 ⋯   6177.9399  -5645.12177  4284.2547    3272.30193  3071.11428 -4590.2494
104 ⋯  19044.7009  13575.20768 -4344.5543    -648.03952 -1530.21478  -883.7059
105 ⋯ -19679.5353   7110.58099   749.8511   -5645.09614  2171.92187  -485.6537
106 ⋯  -5493.0758    620.81545 -2018.3381    2223.07919   712.53961 -1253.7255
107 ⋯  -8734.4273   1527.81396  2828.5117   -6676.72912  2674.59120   115.4793
108 ⋯  -6428.8993  -2896.47991  -682.2415    2625.28667  1760.86947 -1876.6063
109 ⋯  -1002.5857  -5227.84836 12550.9056    9475.62591 -4923.03689  3676.2841
110 ⋯   2334.8180   -825.62144  5805.6530   -8566.35721  3450.90165 -1473.9779
111 ⋯  12346.4340  -8301.28415  5899.8057  -11343.84066  6632.07606  1279.9264
112 ⋯   5458.6852  -3738.59414  6959.8105   -9300.84340  3015.85523  -963.3134
113 ⋯  18762.7174   9560.78487 -3253.0747     941.05544   -94.98439  -844.7054
114 ⋯ -12266.2221   1669.07950  -651.9477   -5563.15207  3788.04962  2216.3039
115 ⋯  -9543.2885  -1540.15901 -5413.9108     722.65198  2726.77801  2000.0902
116 ⋯  -5503.0361  -1806.94326 -4699.7842     744.77154  2825.96558  2318.8025
117 ⋯  -3018.1631   -278.59968 -3248.3278    1585.05673  3066.83322   784.0049
118 ⋯  -2515.7837  -3687.57424  2575.2438   -6968.87763  2944.16736   743.2566
119 ⋯  15610.0607 -15867.58274 -3820.5211   -2744.46893  3953.10760  4734.4564
120 ⋯   4775.1818  -3356.95245 -1788.4443    2012.39638  2340.35039  -133.2073
121 ⋯  17855.8765  14659.29592 -7425.1173    -541.27105 -1568.03160  -355.2795
122 ⋯ -11753.7610   1275.82081  2439.2490   -6047.09124  1735.72351 -1127.1592
123 ⋯  -6361.1745   -445.10785 -1796.6221    1114.95509 -1194.96639 -2811.9636
    Hannum   Horvath1 PhenoAge    epiTOC2
1   18.73410 43.97707  -3.2600031  738.4980
2   11.48559 43.30013   2.1732831  855.6126
3   21.34757 49.79894  -2.0383794 1039.6543
4   20.43901 37.99854   1.9195821  951.4873
5   27.52843 44.14654 -10.6833841 1037.1281
6   29.39186 49.12554  -1.9751743  994.0742
7   27.32664 50.02112   9.6122992 1138.7123
8    8.95954 39.38449   0.8140172  601.3421
9   22.09779 47.38520   0.6649717 1065.5823
10  24.73726 53.24506   7.5877401 1357.9041
11  25.27241 57.24240  -0.5903807 1378.5939
12  14.89334 38.08402  -4.8255412 1529.6055
13  10.41064 28.39451 -16.2811951 1103.2912
14  22.52661 48.74586  -5.7410288 1348.1337
15  22.11011 51.27316   1.1052871 1231.8878
16  26.30035 48.64327   5.4344666 1016.7794
17  12.73504 40.32769   1.6204610  609.5236
18  28.36435 59.95054   1.3817402 2196.2159
19  19.11259 49.71735  10.3411917 2147.9438
20  21.18987 50.21803   4.7008468  945.7457
21  21.32236 45.10961  -3.9151252 2041.9534
22  26.68956 59.76066   9.5603367 1154.5314
23  27.04327 45.05661  15.0814792 2155.9608
24  10.55537 28.57497 -10.8786320 1296.3098
25  21.19578 49.46287   2.7330935  969.8594
26  22.44920 48.85632  -1.9883047 1072.2241
27  20.59617 47.18572   9.5779526 1440.4729
28  17.76713 34.44831  -6.5206101  941.6604
29  23.84309 56.21754  -0.5525658 1039.8704
30  11.45757 35.00470   0.1116835 1155.7779
⋮   ⋮        ⋮        ⋮           ⋮
94  31.82229 65.51312  -2.5823018 1476.2432
95  21.92683 46.77352  -8.3625780 1513.8764
96  22.00352 48.26175 -12.4797308  684.6836
97  28.88147 56.86657  -3.8171289 1333.4103
98  25.67917 50.70308  -4.9351181 1504.6646
99  29.81933 57.61777   3.5226753 1527.4731
100 14.72254 41.06623 -12.0657323 1264.9627
101 19.24702 36.14543 -17.5063968 1486.9321
102 32.77856 62.94971   0.3323626 1832.1195
103 22.11432 50.87764  -8.5662288 1550.7115
104 29.02941 56.69559  -2.1337691 1241.1859
105 16.38609 39.16766  -7.3506901  786.5176
106 29.33811 55.44037   0.2560954 1433.1469
107 17.94961 41.55240  -0.5786184 1402.5849
108 27.60813 62.22694  -0.4440083 1428.1831
109 23.80318 48.51556  -6.7538054 1259.2149
110 22.66868 45.68881  -8.0919183 1479.5319
111 26.59207 64.17989 -11.8215712 2242.5372
112 27.15620 59.45176  -4.5574065 1607.7768
113 14.07225 51.52015  -6.8181633 1151.4540
114 26.73630 62.75045   3.6570852 1254.0124
115 26.31859 52.63579  -3.1575856 1353.8044
116 14.12195 29.41185 -18.8205935 1239.6499
117 22.17187 45.40558 -10.8536852 1376.2340
118 31.27730 62.15193   0.5896353 1698.0315
119 14.31692 44.64628  15.3355717 3506.7201
120 22.24880 47.78256 -12.8249623 1431.9458
121 15.80621 29.12713 -29.5774918  859.1484
122 26.90923 60.30378  -4.4028300 1450.2797
123 27.14882 55.94698   4.9257537 1878.0844

In [59]:
# Preparing data for stochastic clock
beta_m = as.matrix(t(beta))
age = as.vector(pheno$Age)
dim(beta_m)
dim(age)
head(colnames(beta_m))  # Should be sample IDs

[1] 865918    123

NULL

[1] "BRA_201465920012_R01C01" "BRA_201465920012_R02C01"
[3] "BRA_201465920012_R03C01" "BRA_201465920012_R04C01"
[5] "BRA_201465920012_R05C01" "BRA_201465920012_R06C01"

In [60]:
# Running stocastic clocks
clockpath = "/vast/palmer/scratch/montalvo-ortiz/jjm262/00tclocks/00uthealth/03scripts/01epigenome/glmStocALL.Rd"

# This is the function for stochastic clocks
RunStochClocks <- function(data.m,ages.v=NULL,refM.m=NULL){
 load(clockpath); ## load in stochastic clock information
 estF.m <- NULL;
 if(!is.null(refM.m)){
   estF.m <- epidish(data.m,ref=refM.m,method="RPC",maxit=500)$est;
 }
 predMage.lv <- list();
 eaa.lv <- list();
 iaa.lv <- list();
 for(c in 1:length(glmStocALL.lo)){
  glm.o <- glmStocALL.lo[[c]];
  coef.m <- coef(glm.o);
  intC <- coef.m[1,ncol(coef.m)]; ### intercept term
  coef.v <- coef.m[-1,ncol(coef.m)]; ### estimated regression coefficients
  commonCpGs.v <- intersect(names(coef.v),rownames(data.m));
  rep.idx <- match(commonCpGs.v,names(coef.v));
  map.idx <- match(commonCpGs.v,rownames(data.m));
  predMage.lv[[c]] <- as.vector(intC + matrix(coef.v[rep.idx],nrow=1) %*% data.m[map.idx,]);
  if(!is.null(ages.v)){
     eaa.lv[[c]] <- lm(predMage.lv[[c]] ~ ages.v)$res;     
     if(!is.null(refM.m)){
      iaa.lv[[c]] <- lm(predMage.lv[[c]] ~ ages.v + estF.m)$res;
     }
  }
 }
 return(list(mage=predMage.lv,eaa=eaa.lv,iaa=iaa.lv,estF=estF.m));
}

# Running function
sclocks = RunStochClocks(beta_m, age)

In [75]:
# Add sample IDs first (these are the column names of beta)
sample_ids <- colnames(beta_m)

mage_df <- as.data.frame(do.call(cbind, sclocks$mage))
colnames(mage_df) <- paste0("StochClock", seq_along(sclocks$mage))
mage_df$name <- sample_ids

eaa_df <- as.data.frame(do.call(cbind, sclocks$eaa))
colnames(eaa_df) <- paste0("EAA_StochClock", seq_along(sclocks$eaa))
eaa_df$name <- sample_ids

# Merge side by side by 'name'
combined_df <- merge(mage_df, eaa_df, by = "name")
combined_df
pheno = merge(pheno, mage_df, by = c('name'))
pheno

    name                    StochClock1 StochClock2 StochClock3 EAA_StochClock1
1   BRA_201465920012_R01C01 39.59430    22.391614   57.06745      3.9628005
2   BRA_201465920012_R02C01 34.52284    24.065296   60.98985      1.9302871
3   BRA_201465920012_R03C01 43.22477    16.941543   52.77841      5.3140622
4   BRA_201465920012_R04C01 31.90022    17.266903   56.09438     -1.7053117
5   BRA_201465920012_R05C01 39.15640    19.215417   53.88648      2.5119189
6   BRA_201465920012_R06C01 32.98630    22.640571   57.32405     -4.6711597
7   BRA_201465920012_R07C01 39.03303    26.391507   60.44997     -1.6633780
8   BRA_201465920012_R08C01 33.02133    22.930111   53.04305      0.1755288
9   BRA_201465920048_R01C01 41.99910    24.106571   45.90228      4.8481276
10  BRA_201465920048_R02C01 40.13719    35.820643   50.32745      0.2005205
11  BRA_201465920048_R03C01 43.11292    26.406093   52.31966      4.6957284
12  BRA_201465920048_R04C01 29.92229    25.100280   50.83494     -3.4299943
13  BRA_201465920048_R05C01 21.97245     2.393555   48.92312     -7.3279096
14  BRA_201465920048_R06C01 32.73736    28.962461   51.06176     -5.6798312
15  BRA_201465920048_R07C01 28.43877    14.896925   40.30945     -8.9654410
16  BRA_201465920048_R08C01 34.31748    20.153055   55.08932     -4.8594538
17  BRA_201532190145_R01C01 34.53192    19.119408   58.51624      2.1926111
18  BRA_201532190145_R02C01 47.36015    42.499411   59.69293      5.3975147
19  BRA_201532190145_R03C01 37.48201    33.563688   62.60442      0.8375360
20  BRA_201532190145_R04C01 38.15180    34.564478   61.27870     -0.2653916
21  BRA_201532190145_R05C01 33.02420    24.612449   57.85924     -4.8865070
22  BRA_201532190145_R06C01 47.13845    44.806643   59.07253      4.9225730
23  BRA_201532190145_R07C01 26.10401    23.422130   45.69590    -12.5664267
24  BRA_201532190145_R08C01 32.47675     1.374313   52.89688      2.4166555
25  BRA_202273260185_R01C01 42.15820    34.079284   68.35046      4.5007353
26  BRA_202273260185_R02C01 40.86755    19.347812   53.48648      4.4763168
27  BRA_202273260185_R03C01 35.01082    30.693587   59.96235     -0.8739202
28  BRA_202273260185_R04C01 27.62863    10.158510   52.66632     -3.9509376
29  BRA_202273260185_R05C01 37.96498    29.676813   61.49696     -2.2249379
30  BRA_202273260185_R06C01 30.27640     8.895619   48.42661      0.9760328
⋮   ⋮                       ⋮           ⋮           ⋮           ⋮
94  BRA_205062740052_R06C01 45.69210     28.542006  57.61931      6.2619268
95  BRA_205062740052_R07C01 38.37963     17.253424  57.81197      4.0143612
96  BRA_205062740052_R08C01 31.32908     11.797226  48.33513     -6.3283842
97  BRA_205062740070_R01C01 41.37117     23.832210  58.20783      2.1942374
98  BRA_205062740070_R02C01 44.22862     20.032583  60.00325      8.8503646
99  BRA_205062740070_R03C01 41.22090     26.666568  54.70808     -0.7417339
100 BRA_205062740070_R04C01 32.18811      3.080833  53.37116      2.1280158
101 BRA_205062740070_R05C01 32.04569      6.240488  51.86675      1.7323462
102 BRA_205062740070_R06C01 45.89801     29.812229  57.06722      3.6821363
103 BRA_205062740070_R07C01 35.10275     18.108861  54.76620     -0.7819884
104 BRA_205062740070_R08C01 38.76694     16.757187  41.54861     -1.6762173
105 BRA_205062740140_R01C01 38.49818     13.119151  63.90384      7.9315897
106 BRA_205096370081_R01C01 41.39955     31.009218  59.19039      1.2096397
107 BRA_205096370081_R02C01 36.17200     22.848278  61.82084      4.5924309
108 BRA_205096370081_R03C01 42.74728     30.455617  59.96736      2.0508746
109 BRA_205096370081_R04C01 38.99798     18.803898  49.45354      4.3794692
110 BRA_205096370081_R05C01 33.98523     15.703245  55.09175     -0.8865290
111 BRA_205096370081_R06C01 35.42976     12.042655  52.46101     -0.7082310
112 BRA_205096370081_R07C01 42.65755     27.917025  53.12348      1.9611499
113 BRA_205096370081_R08C01 25.07492     28.101226  47.08869    -14.8617504
114 BRA_205096370104_R01C01 44.58492     27.983587  61.30537      4.9014934
115 BRA_205096370104_R02C01 39.14184     29.140442  59.84140      2.4973607
116 BRA_205096370104_R03C01 27.10943      1.955248  51.79309     -2.1909348
117 BRA_205096370104_R04C01 31.80577     14.784553  54.35859     -2.0530135
118 BRA_205096370104_R05C01 45.03989     31.787648  56.26473      4.0902411
119 BRA_205096370104_R06C01 10.31422     20.750732  50.10969    -24.8107833
120 BRA_205096370104_R07C01 35.33793     12.708812  50.38493     -0.2935641
121 BRA_205096370104_R08C01 21.99008    -10.118879  35.05222     -9.5894931
122 BRA_205134980005_R01C01 44.30638     29.480630  56.86554      3.1034857
123 BRA_205134980005_R02C01 45.64196     28.633848  52.51194      4.9455603
    EAA_StochClock2 EAA_StochClock3
1    2.6042783        2.7030551
2   10.0491274        6.9936651
3   -7.1741671       -1.8621434
4    1.3270119        1.9754579
5   -2.4956410       -0.6006489
6   -0.9942085        2.7141787
7   -3.0144396        5.4718892
8    8.4330115       -0.9838217
9    1.4336525       -8.6462190
10   7.8574879       -4.5585810
11   1.3285215       -2.3822667
12   9.6413192       -3.2532976
13  -5.3705163       -4.6741700
14   3.8848892       -3.6401654
15  -8.2569245      -14.2697335
16  -6.3673083        0.2953475
17   5.5841699        4.5507414
18  10.6888115        4.5614306
19  11.8526305        8.1172832
20   9.4869059        6.5767773
21   0.4967383        3.2186854
22  12.5151131        3.9103435
23  -2.1363724       -9.0367092
24  -7.8325504       -0.7924662
25  10.4445036       13.7405915
26  -1.8823154       -0.9699674
27  10.4253215        5.5672730
28  -1.9339365       -1.2071278
29   1.2327277        6.5802440
30   1.1315475       -5.1706813
⋮   ⋮               ⋮
94    1.5407126       2.7946466
95   -0.1292585       3.6009977
96  -11.8375542      -6.2747362
97   -2.6881536       3.4138579
98    0.7261786       5.6695397
99   -5.1440312      -0.4234217
100  -6.1260300      -0.3181820
101  -3.4473055      -1.8532758
102  -2.4793013       1.9050326
103  -2.1594046       0.3711194
104 -12.1678290     -13.3987826
105   2.9504265      10.1531308
106   2.5651324       4.2736811
107  10.7558320       7.9473874
108   1.0496701       4.9892810
109   0.9402844      -4.7881153
110  -2.6412988       0.8194018
111  -8.7065420      -1.9647597
112  -1.4889217      -1.8546031
113   0.1380705      -7.7973359
114   0.5013627       6.4500291
115   7.4293842       5.3542670
116  -5.8088235      -1.8042057
117  -1.6362684       0.2089829
118   1.9007711       1.2559601
119   1.9252579      -4.1933341
120  -7.0785232      -3.9794668
121 -22.2113249     -18.8212270
122  -0.8871775       1.8260859
123  -0.7720992      -2.4661389

    name                    SAB   Sentrix_ID          Year Ethnicity Gender Age
1   BRA_201465920012_R01C01 67917 201465920012_R01C01 2018 Hispanic  Male   44
2   BRA_201465920012_R02C01 67927 201465920012_R02C01 2018 Black     Female 32
3   BRA_201465920012_R03C01 67928 201465920012_R03C01 2018 Black     Male   53
4   BRA_201465920012_R04C01 67929 201465920012_R04C01 2018 White     Female 36
5   BRA_201465920012_R05C01 67930 201465920012_R05C01 2018 White     Male   48
6   BRA_201465920012_R06C01 67931 201465920012_R06C01 2018 White     Male   52
7   BRA_201465920012_R07C01 67941 201465920012_R07C01 2018 White     Male   64
8   BRA_201465920012_R08C01 67943 201465920012_R08C01 2018 White     Male   33
9   BRA_201465920048_R01C01 67944 201465920048_R01C01 2018 White     Female 50
10  BRA_201465920048_R02C01 67945 201465920048_R02C01 2018 Black     Male   61
11  BRA_201465920048_R03C01 67933 201465920048_R03C01 2018 White     Female 55
12  BRA_201465920048_R04C01 67935 201465920048_R04C01 2018 White     Male   35
13  BRA_201465920048_R05C01 67938 201465920048_R05C01 2018 Black     Male   19
14  BRA_201465920048_R06C01 67940 201465920048_R06C01 2018 White     Male   55
15  BRA_201465920048_R07C01 67946 201465920048_R07C01 2018 White     Male   51
16  BRA_201465920048_R08C01 67948 201465920048_R08C01 2018 Hispanic  Male   58
17  BRA_201532190145_R01C01 67974 201532190145_R01C01 2018 White     Female 31
18  BRA_201532190145_R02C01 67976 201532190145_R02C01 2018 White     Female 69
19  BRA_201532190145_R03C01 67977 201532190145_R03C01 2018 White     Female 48
20  BRA_201532190145_R04C01 67978 201532190145_R04C01 2018 White     Female 55
21  BRA_201532190145_R05C01 67979 201532190145_R05C01 2018 White     Female 53
22  BRA_201532190145_R06C01 67980 201532190145_R06C01 2018 White     Female 70
23  BRA_201532190145_R07C01 67909 201532190145_R07C01 2018 Black     Male   56
24  BRA_201532190145_R08C01 67915 201532190145_R08C01 2018 White     Male   22
25  BRA_202273260185_R01C01 67926 202273260185_R01C01 2018 Hispanic  Male   52
26  BRA_202273260185_R02C01 67937 202273260185_R02C01 2018 White     Male   47
27  BRA_202273260185_R03C01 67968 202273260185_R03C01 2018 Black     Female 45
28  BRA_202273260185_R04C01 67969 202273260185_R04C01 2018 Black     Male   28
29  BRA_202273260185_R05C01 67970 202273260185_R05C01 2018 White     Male   62
30  BRA_202273260185_R06C01 67971 202273260185_R06C01 2018 Black     Male   19
⋮   ⋮                       ⋮     ⋮                   ⋮    ⋮         ⋮      ⋮
94  BRA_205062740052_R06C01 67994 205062740052_R06C01 2022 Hispanic  Male   59
95  BRA_205062740052_R07C01 67982 205062740052_R07C01 2022 White     Male   39
96  BRA_205062740052_R08C01 67990 205062740052_R08C01 2022 White     Male   52
97  BRA_205062740070_R01C01 79220 205062740070_R01C01 2022 White     Male   58
98  BRA_205062740070_R02C01 67985 205062740070_R02C01 2022 White     Male   43
99  BRA_205062740070_R03C01 79225 205062740070_R03C01 2022 Black     Female 69
100 BRA_205062740070_R04C01 79218 205062740070_R04C01 2022 Black     Male   22
101 BRA_205062740070_R05C01 79200 205062740070_R05C01 2022 White     Male   23
102 BRA_205062740070_R06C01 79213 205062740070_R06C01 2022 Black     Male   70
103 BRA_205062740070_R07C01 79209 205062740070_R07C01 2022 White     Male   45
104 BRA_205062740070_R08C01 79205 205062740070_R08C01 2022 White     Male   63
105 BRA_205062740140_R01C01 67983 205062740140_R01C01 2022 White     Female 24
106 BRA_205096370081_R01C01 79214 205096370081_R01C01 2022 White     Male   62
107 BRA_205096370081_R02C01 79229 205096370081_R02C01 2022 Black     Male   28
108 BRA_205096370081_R03C01 67999 205096370081_R03C01 2022 White     Male   64
109 BRA_205096370081_R04C01 79228 205096370081_R04C01 2022 White     Male   40
110 BRA_205096370081_R05C01 79226 205096370081_R05C01 2022 Black     Female 41
111 BRA_205096370081_R06C01 79230 205096370081_R06C01 2022 Black     Female 46
112 BRA_205096370081_R07C01 67992 205096370081_R07C01 2022 Black     Female 64
113 BRA_205096370081_R08C01 67997 205096370081_R08C01 2022 Hispanic  Male   61
114 BRA_205096370104_R01C01 79221 205096370104_R01C01 2022 Black     Female 60
115 BRA_205096370104_R02C01 79216 205096370104_R02C01 2022 White     Male   48
116 BRA_205096370104_R03C01 79217 205096370104_R03C01 2022 Hispanic  Male   19
117 BRA_205096370104_R04C01 67984 205096370104_R04C01 2022 White     Male   37
118 BRA_205096370104_R05C01 79212 205096370104_R05C01 2022 Black     Female 65
119 BRA_205096370104_R06C01 79201 205096370104_R06C01 2022 Hispanic  Male   42
120 BRA_205096370104_R07C01 79215 205096370104_R07C01 2022 Hispanic  Male   44
121 BRA_205096370104_R08C01 67998 205096370104_R08C01 2022 White     Male   28
122 BRA_205134980005_R01C01 79238 205134980005_R01C01 2022 Black     Female 66
123 BRA_205134980005_R02C01 79239 205134980005_R02C01 2022 Black     Male   64
    PMIhrs pH
1   32.67  5.91
2   31.57  6.56
3   28.65  6.79
4   28.20  6.80
5   31.30  6.44
6   31.92  6.38
7   26.35  6.40
8   10.57  6.72
9    9.55  6.63
10  37.40  6.64
11  28.78  7.02
12  18.20  6.20
13  36.03  6.63
14  23.75  5.84
15  22.98  6.73
16  26.48  6.82
17  23.60  6.56
18  24.82  6.42
19  31.97  6.73
20  27.62  6.40
21  30.15  6.89
22  28.60  6.57
23  30.25  6.48
24  53.82  6.63
25  47.92  6.49
26  27.62  6.23
27  13.07  6.49
28  23.97  6.68
29  23.82  7.29
30  21.60  7.05
⋮   ⋮      ⋮
94  32.35  6.80
95  16.52  6.53
96  23.43  6.77
97  15.05    NA
98  25.17  6.44
99  20.32    NA
100 22.10    NA
101 16.78  6.52
102 27.32    NA
103 20.63    NA
104 14.55    NA
105 14.50  6.50
106 24.28    NA
107 39.83    NA
108 43.33  6.53
109 33.48    NA
110 38.70    NA
111 12.32    NA
112 28.03  6.62
113 26.38  6.89
114 23.80    NA
115 13.17    NA
116 28.88    NA
117 11.73  6.04
118 19.25    NA
119 33.45    NA
120 56.92    NA
121 32.33  7.02
122 23.83    NA
123 44.73    NA
    Cause_of_Death
1   acute carisoprodol toxicity
2   undetermined
3   acute toxicity of cocaine and ethanol
4   toxic effects of methadone
5   GSW
6   cardiovascular disease, not opioid
7   ruptured AAA
8   multi overdose: benzodiazepine, amphetamine, cocaine, EtOH, and opioid
9   sepsis
10  Cardiovascular disease
11  carciovascular disease
12  combined toxicity of heroin, methamphetamine, alprazolam and ethanol
13  combined toxic effects of alprazolam, codeine and morphine
14  Cardiovascular disease
15  cocaine and opioid OD
16  Cardiovascular disease
17  opioid, amitriptyline, diphenhydramine, hydroxyzine, promethazine, and benzo OD
18  Cardiovascular disease
19  prescription medication OD
20  opioid, EtOH, benzodiazepine, diphenhydramine and gabapentin OD
21  alcohol and diphenhydramine OD
22  fall
23  Pulmonary Embolism
24  Toxic effects of U-47700
25  Cardiovascular disease
26  Cardiovascular disease
27  toxic effect of cocaine
28  cirrhosis and ESRD
29  Cardiovascular disease with signs of chronic alcoholism (hepatic fibrosis)
30  GSW
⋮   ⋮
94  Cardiovascular disease
95  Cardiovascular disease
96  Cardiovascular disease
97  Acute and chronic ethanolism with toxic effects of chlordiazepoxide
98  toxic effects of methamphetamine
99  Atherosclerotic and hypertensive cardiovascular disease
100 Combined alprazolam, etizolam, and fentanyl toxicities
101 mitragynine, benzodiazepine, and loperamide OD
102 Pulmonary thromboembolism due to deep vein thromboses of lower extremities
103 Acute toxicity due to the combined effects of fentanyl, midazolam, diphenhydramine, amphetamine, and bupropion
104 Suicide due to combined acetaminophen, hydrocodone, zolpidem toxicity
105 opioid, benzodiazepine and SSRI OD
106 Acute Methamphetamine Toxicity
107 Complications of morbid obesity and asthma
108 Cardiovascular disease
109 Combined toxic effects of fentanyl, alprazolam, methamphetamine, and MDMA
110 hypertensive and atherosclerotic cardiovascular disease
111 Toxic effects of fentanyl, codeine, hydrocodone, quetiapine, and diphenhydramine
112 Cardiovascular disease
113 Cardiovascular disease
114 Acute cocaine toxicity
115 Combined toxic effects of heroin, methamphetmine, mitragynine and ethanol
116 Toxic effects of fentanyl, alprazolam, and tramadol
117 diabetic ketoacidosis
118 Suicide due to toxic effects of cyclobenzaprine with diazepam
119 GSW
120 Bilateral pulmonary thromboemboli due to deep vein thrombosis associated with obesity
121 cocaine, opioid, and benzodiazepine OD
122
123
    ⋯ PC5         PC6          PC7         PC8         StochClock1.x
1   ⋯ -5005.23120  2870.01084  -3640.1573     355.5046 39.59430
2   ⋯ -1485.83904 -6463.84352  -1715.2361    2302.3781 34.52284
3   ⋯ -5556.49206  1126.86676  -4362.8206    1257.2628 43.22477
4   ⋯ -2082.82146 -4780.32599  -5395.5371   -1540.2280 31.90022
5   ⋯ -5945.75523 -1059.95173  -6963.1584    2966.0035 39.15640
6   ⋯ -4522.12854    -3.86258  -3440.9959    1329.0686 32.98630
7   ⋯  1858.70118  1448.24412  -2024.6519   -2061.6679 39.03303
8   ⋯ -4462.38435  1794.73226   -820.1338   -1034.7168 33.02133
9   ⋯ -1597.55280 -3680.88142  -1699.2859     590.2310 41.99910
10  ⋯ -2633.85702   104.38850   -651.0705     785.4020 40.13719
11  ⋯ -2748.52840 -5500.57009  -1450.3660    2324.3621 43.11292
12  ⋯ -1727.96346   664.14644  -3581.3157     748.0825 29.92229
13  ⋯ -6634.48625  -126.30027  -3778.0404    2460.2815 21.97245
14  ⋯ -6768.00352  1090.65423  -4380.7075    3853.5769 32.73736
15  ⋯  -368.00075  -158.13531  -4448.5568   -2980.1615 28.43877
16  ⋯  -651.91646  -197.09408  -3487.1416   -4920.1739 34.31748
17  ⋯ -1541.96995 -7021.36954  -4268.7950     242.5200 34.53192
18  ⋯  1062.44685 -7196.46637  -2310.5949   -1260.0535 47.36015
19  ⋯   227.01424 -9042.59180  -1863.8628     -17.4089 37.48201
20  ⋯ -1924.34607 -6663.13564  -3845.6939    2143.3157 38.15180
21  ⋯   775.57175 -6169.68920  -6128.8901    2418.3444 33.02420
22  ⋯  -773.01517 -8771.18635  -4224.2191    1047.9742 47.13845
23  ⋯ 11672.09558  -533.80167  -2558.0157  -14390.6189 26.10401
24  ⋯ -3315.39766  1921.07597  -4264.9230    -988.8265 32.47675
25  ⋯ -1948.08147  3231.91539    805.3035   -2206.1611 42.15820
26  ⋯ -3389.66329  1019.22236  -3518.0092     -80.0354 40.86755
27  ⋯  5030.79793 -3572.62139   2330.7556    1098.7878 35.01082
28  ⋯   -94.92674  1311.77378    361.8461     705.0002 27.62863
29  ⋯   489.29650  2828.85051   1542.7420   -2450.5514 37.96498
30  ⋯  2430.38115  1468.61301   3103.0225     321.1489 30.27640
⋮   ⋱ ⋮           ⋮            ⋮           ⋮           ⋮
94  ⋯  2144.5417    4639.09444  1805.01144 -2425.4879  45.69210
95  ⋯  -705.7584    2078.43860  1363.82925 -1793.1447  38.37963
96  ⋯ -6009.4811      78.25589 -2903.82228 -4242.8403  31.32908
97  ⋯  2307.8286    4353.64030  3091.82810  -868.9399  41.37117
98  ⋯   393.8604    3107.90511  2442.38774 -2070.9743  44.22862
99  ⋯  5615.2500   -8039.84903   107.18582 -2076.1262  41.22090
100 ⋯   635.8986    3081.04209  2633.13414 -2487.1951  32.18811
101 ⋯   725.9511    2202.59977   701.35797  1303.0236  32.04569
102 ⋯  1494.0529    2324.93068  2338.79685  -509.2862  45.89801
103 ⋯  4284.2547    3272.30193  3071.11428 -4590.2494  35.10275
104 ⋯ -4344.5543    -648.03952 -1530.21478  -883.7059  38.76694
105 ⋯   749.8511   -5645.09614  2171.92187  -485.6537  38.49818
106 ⋯ -2018.3381    2223.07919   712.53961 -1253.7255  41.39955
107 ⋯  2828.5117   -6676.72912  2674.59120   115.4793  36.17200
108 ⋯  -682.2415    2625.28667  1760.86947 -1876.6063  42.74728
109 ⋯ 12550.9056    9475.62591 -4923.03689  3676.2841  38.99798
110 ⋯  5805.6530   -8566.35721  3450.90165 -1473.9779  33.98523
111 ⋯  5899.8057  -11343.84066  6632.07606  1279.9264  35.42976
112 ⋯  6959.8105   -9300.84340  3015.85523  -963.3134  42.65755
113 ⋯ -3253.0747     941.05544   -94.98439  -844.7054  25.07492
114 ⋯  -651.9477   -5563.15207  3788.04962  2216.3039  44.58492
115 ⋯ -5413.9108     722.65198  2726.77801  2000.0902  39.14184
116 ⋯ -4699.7842     744.77154  2825.96558  2318.8025  27.10943
117 ⋯ -3248.3278    1585.05673  3066.83322   784.0049  31.80577
118 ⋯  2575.2438   -6968.87763  2944.16736   743.2566  45.03989
119 ⋯ -3820.5211   -2744.46893  3953.10760  4734.4564  10.31422
120 ⋯ -1788.4443    2012.39638  2340.35039  -133.2073  35.33793
121 ⋯ -7425.1173    -541.27105 -1568.03160  -355.2795  21.99008
122 ⋯  2439.2490   -6047.09124  1735.72351 -1127.1592  44.30638
123 ⋯ -1796.6221    1114.95509 -1194.96639 -2811.9636  45.64196
    StochClock2.x StochClock3.x StochClock1.y StochClock2.y StochClock3.y
1   22.391614     57.06745      39.59430      22.391614     57.06745
2   24.065296     60.98985      34.52284      24.065296     60.98985
3   16.941543     52.77841      43.22477      16.941543     52.77841
4   17.266903     56.09438      31.90022      17.266903     56.09438
5   19.215417     53.88648      39.15640      19.215417     53.88648
6   22.640571     57.32405      32.98630      22.640571     57.32405
7   26.391507     60.44997      39.03303      26.391507     60.44997
8   22.930111     53.04305      33.02133      22.930111     53.04305
9   24.106571     45.90228      41.99910      24.106571     45.90228
10  35.820643     50.32745      40.13719      35.820643     50.32745
11  26.406093     52.31966      43.11292      26.406093     52.31966
12  25.100280     50.83494      29.92229      25.100280     50.83494
13   2.393555     48.92312      21.97245       2.393555     48.92312
14  28.962461     51.06176      32.73736      28.962461     51.06176
15  14.896925     40.30945      28.43877      14.896925     40.30945
16  20.153055     55.08932      34.31748      20.153055     55.08932
17  19.119408     58.51624      34.53192      19.119408     58.51624
18  42.499411     59.69293      47.36015      42.499411     59.69293
19  33.563688     62.60442      37.48201      33.563688     62.60442
20  34.564478     61.27870      38.15180      34.564478     61.27870
21  24.612449     57.85924      33.02420      24.612449     57.85924
22  44.806643     59.07253      47.13845      44.806643     59.07253
23  23.422130     45.69590      26.10401      23.422130     45.69590
24   1.374313     52.89688      32.47675       1.374313     52.89688
25  34.079284     68.35046      42.15820      34.079284     68.35046
26  19.347812     53.48648      40.86755      19.347812     53.48648
27  30.693587     59.96235      35.01082      30.693587     59.96235
28  10.158510     52.66632      27.62863      10.158510     52.66632
29  29.676813     61.49696      37.96498      29.676813     61.49696
30   8.895619     48.42661      30.27640       8.895619     48.42661
⋮   ⋮             ⋮             ⋮             ⋮             ⋮
94   28.542006    57.61931      45.69210       28.542006    57.61931
95   17.253424    57.81197      38.37963       17.253424    57.81197
96   11.797226    48.33513      31.32908       11.797226    48.33513
97   23.832210    58.20783      41.37117       23.832210    58.20783
98   20.032583    60.00325      44.22862       20.032583    60.00325
99   26.666568    54.70808      41.22090       26.666568    54.70808
100   3.080833    53.37116      32.18811        3.080833    53.37116
101   6.240488    51.86675      32.04569        6.240488    51.86675
102  29.812229    57.06722      45.89801       29.812229    57.06722
103  18.108861    54.76620      35.10275       18.108861    54.76620
104  16.757187    41.54861      38.76694       16.757187    41.54861
105  13.119151    63.90384      38.49818       13.119151    63.90384
106  31.009218    59.19039      41.39955       31.009218    59.19039
107  22.848278    61.82084      36.17200       22.848278    61.82084
108  30.455617    59.96736      42.74728       30.455617    59.96736
109  18.803898    49.45354      38.99798       18.803898    49.45354
110  15.703245    55.09175      33.98523       15.703245    55.09175
111  12.042655    52.46101      35.42976       12.042655    52.46101
112  27.917025    53.12348      42.65755       27.917025    53.12348
113  28.101226    47.08869      25.07492       28.101226    47.08869
114  27.983587    61.30537      44.58492       27.983587    61.30537
115  29.140442    59.84140      39.14184       29.140442    59.84140
116   1.955248    51.79309      27.10943        1.955248    51.79309
117  14.784553    54.35859      31.80577       14.784553    54.35859
118  31.787648    56.26473      45.03989       31.787648    56.26473
119  20.750732    50.10969      10.31422       20.750732    50.10969
120  12.708812    50.38493      35.33793       12.708812    50.38493
121 -10.118879    35.05222      21.99008      -10.118879    35.05222
122  29.480630    56.86554      44.30638       29.480630    56.86554
123  28.633848    52.51194      45.64196       28.633848    52.51194

In [77]:
# Save specific objects to an RData file
save(beta, qc, pheno, file = "/vast/palmer/scratch/montalvo-ortiz/jjm262/00tclocks/00uthealth/00databases/05epigenome/00uthealth_brain-07312025.RData")